### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by hex** [hassio-addons/addon-unifi#1]
# Problem/Motivation

How can I install this add-on? It doesn't appear in the add-on store.

**Comment by frenck** [comment]
Hi there @hex,

This add-on is under development and is therefore not yet available in the stable repository.
I'm currently doing some finishing touches and tests. Planning on the final release tonight, which I'm probably going to do on stream.

In case you are interested in the stream:

<https://twitch.tv/internetofthings>

The stream starts around 6:30 PM (UTC).

**Comment by frenck** [comment]
Released! If you refresh your add-on store (goto the add-on store and hit the refresh button in the top right), it should pop up! 🎉
