### ISSUE TITLE
Open GUI through NabuCasa

### ISSUE THREAD

**Issue by michalk-k** [hassio-addons/addon-unifi#100]
I cannot open the controller remotely (using NabuCasa). When I click on Open WEB GUI it opens new tab in browser and then looks like waiting for something... infinitely..
Is it something expected?

With regards

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/88167467-2bd74b80-cc19-11ea-9fb0-1ba5d369a8c0.png)


<https://github.com/hassio-addons/addon-unifi/blob/master/unifi/DOCS.md>
