### ISSUE TITLE
Override Unifi controller version

### ISSUE THREAD

**Issue by chrismccracken** [hassio-addons/addon-unifi#107]
# Problem/Motivation

> I would like to use the latest add-on, but with an older (stable) Unifi controller version (5.x vs 6.x)

## Expected behavior

> Provide config option to select Unifi controller version

## Actual behavior

> Add-on only allows using latest Unifi version (6.0.23 at time of issue submission), which has broken features from prior 5.x versions.

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
You can restore older snapshots of the add-on if you like.
The add-on will not provide such a option.
