### ISSUE TITLE
Failed to start addon 

### ISSUE THREAD

**Issue by JaCoLJcL** [hassio-addons/addon-unifi#108]
# Problem/Motivation

I have a problem to start this addon on this device 

arch | armv7l
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.13
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v7l
python_version | 3.8.5
supervisor | 247
timezone | UTC
version | 0.116.0
virtualenv | false

## Expected behavior

Start this addon on my HA

## Actual behavior

Failed to start addon
Unknown error, see logs

20-10-08 15:38:42 ERROR (SyncWorker_2) [supervisor.docker] Can't start addon_a0d7b954_unifi: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint addon_a0d7b954_unifi (9c993024065caa1f022ada2e861c972faabcdfda0907eb9701794ba20c766f48): Bind for 0.0.0.0:8880 failed: port is already allocated")

## Steps to reproduce

No

## Proposed changes

I want to see a logs of errors on this addon - then I can fix it or get some info about this start error.

**Comment by JaCoLJcL** [comment]
20-10-08 15:38:42 ERROR (SyncWorker_2) [supervisor.docker] Can't start addon_a0d7b954_unifi: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint addon_a0d7b954_unifi (9c993024065caa1f022ada2e861c972faabcdfda0907eb9701794ba20c766f48): Bind for 0.0.0.0:8880 failed: port is already allocated")

**Comment by sinclairpaul** [comment]
> Bind for 0.0.0.0:8880 failed: port is already allocated

Do you have something else listening on this port?

**Comment by JaCoLJcL** [comment]
It seems that my rp is to slow to run this controler
