### ISSUE TITLE
can't stop add on

### ISSUE THREAD

**Issue by hell1337hound** [hassio-addons/addon-unifi#109]
# Problem/Motivation
Cant' halt add on to manually update AP's
> (Why the issue was filed)

## Expected behavior
press stop, it stops
> (What you expected to happen)

## Actual behavior
press stop, thinks about it, stop button goes green, it keeps running
> (What actually happened)

## Steps to reproduce
install latest version on latest OS and build of HA
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
I cannot reproduce this. Please provide logs.

**Comment by alexciurea** [comment]
maybe the watchdog option for this addon is enabled?

**Comment by cray-** [comment]
Probably not helpful, but I can confirm the same issue on with Addon version 0.18.1
Start on boot: disabled.
Watchdog: disabled.
Container behaves as if both of the above have been enabled. Runs on boot and doesn't respond to "STOP" button.
Running latest HassOS on RasPi3. I realise I'm still using 0.18.1 and not latest 0.19.2 but I'm scared to upgrade after recent issues restoring UniFi Controller backup. Will test further on duplicate Pi.

**Comment by sinclairpaul** [comment]
To confirm, can you check the Unifi UI is still available?

I see a lag on the Addon/Supervisor UI, but the addon is actually stopped.  If you wait and then refresh the page it should reflect that.
