### ISSUE TITLE
Unable to connect error when using unifi 6.0

### ISSUE THREAD

**Issue by dorgan** [hassio-addons/addon-unifi#116]
# Problem/Motivation

> When trying to connect this with unifi 6.0 controller the error "Unable to Connect" is recieved 

## Expected behavior

> Integration should be able to use 6.0 controller

## Actual behavior

> Unable to connect error

## Steps to reproduce

> Try to integrate with controller running 6.0

**Comment by frenck** [comment]
This is an add-on, not an integration.

**Comment by dorgan** [comment]
the issue still stands.
<img width="414" alt="Screen Shot 2020-11-21 at 11 23 31 AM" src="https://user-images.githubusercontent.com/464851/99882095-0c165b00-2bec-11eb-8519-9af900a5c1ad.png">

**Comment by frenck** [comment]
No it doesn't. You are showing a screenshot of Home Assistant. If you have an issue with Home Assistant, please report it with Home Assistant.

This repository provides an add-on, which is the UniFi controller application itself, which does not look like that at all.

**Comment by stocker85** [comment]
@dorgan im integrating with 6.1.26 so it is working, maybe have a look at your setup and ask for help on the discord.
