### ISSUE TITLE
Do not work in 64bit mode on RPi4

### ISSUE THREAD

**Issue by QbaF** [hassio-addons/addon-unifi#119]
# Problem/Motivation

Switching to 64 bit (with `arm_64bit=1` in `/boot/config.txt`) cause add-on stop working. 
Add-on logs looks as it is started but ip:8443 lead to ERROR `ERR_CONNECTION_REFUSED`

## Steps to reproduce

Switching to 64 bit with `arm_64bit=1` in /boot/config.txt

## Additional 
When in 64 bit mode
- RPi is indicating: `Linux raspberrypi 5.4.77-v8+ #1371`
- addon-on is indicating: `System: Raspbian GNU/Linux 10 (buster)  (armv7 / raspberrypi4)`

## Environment
Raspberry Pi 4
 Add-on version: 0.19.2
 System: Raspbian GNU/Linux 10 (buster)  (armv7 / raspberrypi4)
 Home Assistant Core: 0.118.4
 Home Assistant Supervisor: 2020.11.0

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/100856066-3a692580-348b-11eb-8ba2-0a0635563ccf.png)

That is not making your OS 64 bits...

Furthermore, the system you are running is not supported by the project.

**Comment by QbaF** [comment]
> That is not making your OS 64 bits...
OK. Does this semantic problem matter in diagnosis or it is just note?

> Furthermore, the system you are running is not supported by the project.
As this is not clear (looks like not only for me), does it meant that `unsupported versions` (eg. versions on Raspbian) will be not solved if regarded to the Supervisor or not solved for ANY issue?

**Comment by frenck** [comment]
You set: `arm_64bit=1`
Yet your OS reports as: `System: Raspbian GNU/Linux 10 (buster) (armv7 / raspberrypi4)`

All your OS is 32 bits based software. It doesn't add up what you are doing there. If you want to run a 64 bits system, run a 64 bits OS. Simple as that.

> As this is not clear (looks like not only for me), does it meant that unsupported versions (eg. versions on Raspbian) will be not solved if regarded to the Supervisor or not solved for ANY issue?

It means that I don't care about those other systems. You are free to run them, but problems are yours.

**Comment by QbaF** [comment]
Ad. "Unsupported": Clear and fair enough
