### ISSUE TITLE
Access to config.gateway.json in sites configuration

### ISSUE THREAD

**Issue by pho3nixf1re** [hassio-addons/addon-unifi#12]
# Problem/Motivation

Need to edit site configuration and provisioning files. Specifically the `config.gateway.json` file on the `default` site. Ideally all sites would be available and the whole `data/sites` folder would be mapped if possible.

## Expected behavior

To be able to access the relevant files from the standard homeassistant folders.

## Actual behavior

Unable to access configuration files.

## Steps to reproduce

n/a

## Proposed changes

Map the sites folder to a location that makes sense that either the smb, ide, or ssh addons can access.

`<unifi_base>/data/sites/<site id: usually just 'default'>/config.gateway.json`

**Comment by frenck** [comment]
Good idea, nevertheless, I don't see this being build on a short term.
Feel free to open a PR.

**Comment by pho3nixf1re** [comment]
I would have already proposed a solution here but I'm unsure of exactly what is possible or makes sense for an addon. Can I simple add a mount point to the container for a path in the homeassistent config? If so, is there a recommended path for addons or other concerns around that?

**Comment by billchurch** [comment]
Need this too and unfortunately it makes the feature unusable if you need to modify any of the config.gateway.json settings... I might take a crack at this at some point, I need to better understand the relationships of the addons with the existing shares.

**Comment by sjtuross** [comment]
Some features cannot be configured through UniFi web interface. **config.gateway.json** is needed for advanced configuration ([https://help.ubnt.com/hc/en-us/articles/215458888-UniFi-USG-Advanced-Configuration](url)). Please find a way to allow putting this file.

**Comment by shbatm** [comment]
I looked a little closer, it looks as if this is already implemented?  According to [this file](https://github.com/hassio-addons/addon-unifi/blob/master/unifi/rootfs/etc/cont-init.d/50-persist-data.sh), you should have a folder in `/usr/share/hassio/addons/data/` on your Hass.io host.  In my case, its `./addons/a0d7b954_unifi/unifi`. Backups are stored in `/usr/share/hassio/backup/unifi`.

**Comment by frenck** [comment]
The main problem with this, is that I have no clue on the site ID.
The only workaround is like @shbatm specified. You'll need to go into the host OS.

Closing this issue, without resolution. Sorry.

**Comment by pho3nixf1re** [comment]
This is the information I was lacking to understand how this works. It seems like it would be backed up with hass as it currently stands which was something I was concerned about. Since that is the case then I agree this is a non-issue
