### ISSUE TITLE
Do not work in 64bit mode on RPi4 'ERROR ERR_CONNECTION_REFUSED'

### ISSUE THREAD

**Issue by QbaF** [hassio-addons/addon-unifi#120]
# Problem/Motivation

I did have a similar problem with this Addon on Raspbian [issue#119](https://github.com/hassio-addons/addon-unifi/issues/119)

It was an unsupported version, so I did migrate to the Supported one. Unfortunately, the problem remains.
Add-on logs look as it is started but `ip:8443` lead to `ERROR ERR_CONNECTION_REFUSED`

And the Add-on is a leader in memory consumption.
![image](https://user-images.githubusercontent.com/57077178/101004092-c1d49880-3560-11eb-9a53-fcf3a6716917.png)
I do not know is it a lot or not, just stating the fact and giving a point of reference. May be useful. 

## Environment
Raspberry Pi4 2GB
 Add-on version: 0.19.3
 You are running the latest version of this add-on.
 System: HassOS 5.6  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 0.118.4
 Home Assistant Supervisor: 2020.12.2

**Comment by frenck** [comment]
Please provide logs

**Comment by QbaF** [comment]
https://pastebin.com/1YdTCF4H

**Comment by QbaF** [comment]
The whole story:
1. It was running under Supervised on Raspbian
2. It stopped working with `ERR_CONNECTION_REFUSED` when switched to `arm_64bit=1` (in /boot/config.txt) [not sure if immediately after that or some time later]
3. works again when switched back to `arm_64bit=0` 
4. after changing the system to HassOS supervised it did works
5. after restoring the backup, it did works
4. after about 1 hour it starts reported CONNECTION REFUSED again

**Comment by frenck** [comment]
`arm_64bit=1` is not something you should do on HassOS. There is like 0 need for that.

**Comment by QbaF** [comment]
`arm_64bit=1` option was on Raspbian.
HassOS was installed on step 4 when I did not receive support for installation on Raspbian.

> There is nothing in this that I can tell anything about what is going on.

So what else you would like from me that can be helpfull in solving issue?

And is that amount of memory used ok?

**Comment by sinclairpaul** [comment]
From the logs the addon is started, although you didn't state, I assume you are connecting via https?

Memory configuration is noted in the documentation https://github.com/hassio-addons/addon-unifi/blob/master/unifi/DOCS.md#option-memory_init

Perhaps looking at a browser dev tools output may be helpful?

**Comment by QbaF** [comment]
No, I use `http` (nginx)

**Comment by sinclairpaul** [comment]
> No, I use http (nginx)

I don't understand what this means, the addon itself is served via SSL.  If you have a proxy in the way, please try troubleshooting without it.

**Comment by QbaF** [comment]
It is working for now. Thank You @sinclairpaul . There are [more users with the issue with this add-ons cooperation](https://community.home-assistant.io/t/home-assistant-community-add-on-unifi-controller/56297/351).

Stopping/uninstalling [NGINX add-on](https://github.com/home-assistant/addons/tree/master/nginx_proxy) without or with rebooting did not work. Only reinstalling then (with reboot) Unifi Controller addon make it.
So something is rasping between these two add-ons.

Can I find somewhere more detailed info about that option-`memory_init`? What is the reason it is 512MB for default? Are there known problems with lowering that number? 
If I understand right, it is just the initial value which is changed then (enlarged rather than reduced) due to UnifiController needs.

BTW: is there a chance to enlarge the SWAP file limit in HassOS supported installation as I notice fulfilling it willingly by Unifi Controller add-on.

**Comment by sinclairpaul** [comment]
I don't see the correlation between the nginx addon and this, so would assume the issue is local configuration.

You can find more details on memory tuning the JVM on both the Unifi and Oracle's site.
