### ISSUE TITLE
Custom configuration

### ISSUE THREAD

**Issue by Mika56** [hassio-addons/addon-unifi#122]
# Problem/Motivation

I have an existing UniFi Controller but want to migrate it to HASS.
This controller has a special configuration for my gateway. Not to get too boring, but I need custom configuration to allow for a VPN tunnel to connect.
On my (Debian) controller, that file is stored in `/usr/lib/unifi/data/sites/default/config.gateway.json`.

## Proposed changes

I'm no expert with HASS and it's plugins. Reading `unifi/rootfs/etc/cont-init.d/unifi.sh`, it looks like `/usr/lib/unifi/data` is a symbolic link to `/data/unifi/data`.
However, I wasn't able to find that `/data` folder via SSH or Samba. `/backup/` is indeed present, but `/data` doesn't seem to be exposed.
Is that something you can work on? Or should I direct that request somewhere else?

**Comment by frenck** [comment]
That is not an issue, but a feature request. I'm not planning on adding support for that. see

#61

**Comment by Mika56** [comment]
Woops, sorry, my brain must've stopped working, didn't see the existing issues

**Comment by frenck** [comment]
Don't worry m8 👍  All good
