### ISSUE TITLE
Expose system.properties parameters (e.g. Xmx and Xms)

### ISSUE THREAD

**Issue by W4v3runn3r** [hassio-addons/addon-unifi#13]
# Problem/Motivation

I would like to be able to control the Java Heap Size as a config option for the addon.  The Add-on sets 
JVM_MAX_HEAP_SIZE=1024M in /usr/lib/unifi/bin/unifi.init.

On smaller single board computers allocating 1024 MB of memory is a lot.  For example, I run HASS.IO on an macbook with 2GB of RAM.

## Proposed changes

Expose the system.properties setting in the Addon Config parameters.  being able to set the Xmx and Xms properties manually.

The Xmx and Xms features are controlled in the unifi.init via the two variable below.  However, they cannot currently be changed.
JVM_MAX_HEAP_SIZE=1024M
JVM_INIT_HEAP_SIZE=

**Comment by frenck** [comment]
>  The Add-on sets JVM_MAX_HEAP_SIZE=1024M in /usr/lib/unifi/bin/unifi.init.

Incorrect. The add-on does not use that file.

Nevertheless, I'll look into exposing the variables.

**Comment by frenck** [comment]
Added memory management option to the add-on configuration and is part of the next release.
