### ISSUE TITLE
Unable to start UniFi Controller after updating to 0.20.0 

### ISSUE THREAD

**Issue by gerasimone** [hassio-addons/addon-unifi#141]
# Problem/Motivation

Got exception trying to start the addons

## Expected behavior

UniFi should start

## Actual behavior

A fatal error has been detected by the Java Runtime Environment:

## Steps to reproduce

Versions:
core-2021.1.4
supervisor-2021.01.5
Home Assistant OS 5.10
UniFi controller  0.20.0 

Configuration:
<pre>
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
log_level: info
memory_max: 1024
memory_init: 512
</pre>

## Error message
<pre>
# Core dump written. Default location: /run/s6/services/unifi/core or core.3233
#
# An error report file with more information is saved as:
# /run/s6/services/unifi/hs_err_pid3233.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
[13:52:49] INFO: Starting the UniFi Controller...
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f93bd92f923, pid=3271, tid=0x00007f93a7cc5700
#
# JRE version: OpenJDK Runtime Environment (8.0_275-b01) (build 1.8.0_275-8u275-b01-0ubuntu1~18.04-b01)
# Java VM: OpenJDK 64-Bit Server VM (25.275-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0xa0a923]
#
# Core dump written. Default location: /run/s6/services/unifi/core or core.3271
#
# An error report file with more information is saved as:
# /run/s6/services/unifi/hs_err_pid3271.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
[13:52:56] INFO: Starting the UniFi Controller...
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f5812327e9e, pid=3309, tid=0x00007f57fc9e8700
#
# JRE version: OpenJDK Runtime Environment (8.0_275-b01) (build 1.8.0_275-8u275-b01-0ubuntu1~18.04-b01)
# Java VM: OpenJDK 64-Bit Server VM (25.275-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x668e9e]
#
# Core dump written. Default location: /run/s6/services/unifi/core or core.3309
#
# An error report file with more information is saved as:
# /run/s6/services/unifi/hs_err_pid3309.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
[13:53:04] INFO: Starting the UniFi Controller...
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000000000, pid=3347, tid=0x00007f266d4b4700
#
# JRE version: OpenJDK Runtime Environment (8.0_275-b01) (build 1.8.0_275-8u275-b01-0ubuntu1~18.04-b01)
# Java VM: OpenJDK 64-Bit Server VM (25.275-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  0x0000000000000000
#
# Core dump written. Default location: /run/s6/services/unifi/core or core.3347
#
# An error report file with more information is saved as:
# /run/s6/services/unifi/hs_err_pid3347.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
[13:53:11] INFO: Starting the UniFi Controller...
Exception in thread "inform_stat-1" java.lang.AbstractMethodError
	at com.ubnt.data.X.put(Unknown Source)
	at com.ubnt.service.devmgr.OO0O.o00000(Unknown Source)
	at com.ubnt.service.devmgr.f.o00000(Unknown Source)
	at com.ubnt.service.devmgr.f.o00000(Unknown Source)
	at com.ubnt.service.devmgr.floatnew$_o.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000000000, pid=3385, tid=0x00007f46279f9700
#
# JRE version: OpenJDK Runtime Environment (8.0_275-b01) (build 1.8.0_275-8u275-b01-0ubuntu1~18.04-b01)
# Java VM: OpenJDK 64-Bit Server VM (25.275-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  0x0000000000000000
#
# Core dump written. Default location: /run/s6/services/unifi/core or core.3385
#
# An error report file with more information is saved as:
# /run/s6/services/unifi/hs_err_pid3385.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
[14:47:12] INFO: Starting the UniFi Controller...
Exception in thread "launcher" java.lang.IllegalStateException: Tomcat failed to start up
	at com.ubnt.net.B.ö00000(Unknown Source)
	at com.ubnt.service.OoOO.øO0000(Unknown Source)
	at com.ubnt.ace.Launcher.main(Unknown Source)
Caused by: java.lang.RuntimeException: Web context failed to initialize
	... 3 more
</pre>

**Comment by frenck** [comment]
Which hardware are you running on?

Could you also dump `ha info` ? Thanks 👍

**Comment by gerasimone** [comment]
Hi Frenck, this is running on Proxmox 6.3-3, the underlying hardware is made by an Asrock embedded mobo and two SSDs, do you need the exact hardware? 
This is the output of the command:
<pre>
➜  ~ ha info                                                           
arch: amd64
channel: stable
docker: 19.03.13
features:
- reboot
- shutdown
- services
- network
- hostname
- hassos
hassos: "5.10"
homeassistant: 2021.1.4
hostname: homeassistant
logging: info
machine: qemux86-64
operating_system: Home Assistant OS 5.10
supervisor: 2021.01.5
supported: true
supported_arch:
- amd64
- i386
timezone: Europe/Rome
</pre>

**Comment by winnerNick** [comment]
I also get this error after upgrade.

![image](https://user-images.githubusercontent.com/6153606/105886461-1e10e180-6013-11eb-8e1d-1e3460c12d7d.png)

**Comment by frenck** [comment]
@winnerNick I don't see how that is even remotely related to anything presented in this issue?

**Comment by archi071** [comment]
I also can't start after updating to version 0.20.1

**Comment by frenck** [comment]
@archi071 Ok, but is it exact some error log? or do you have other issues? Your report sounds a bit generic. Could you clarify?

**Comment by frenck** [comment]
@gerasimone I cannot reproduce it 😢 

The Java runtime is running the latest available. I did bump the add-on with a newer controller version. I could not find a reference there that leads up to this... but worth a shot?

**Comment by gerasimone** [comment]
just updated to the latest version, same issue

<pre>
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: UniFi Controller
 Manage your UniFi network using a web browser
-----------------------------------------------------------
 Add-on version: 0.20.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.10  (amd64 / qemux86-64)
 Home Assistant Core: 2021.1.4
 Home Assistant Supervisor: 2021.01.5
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] unifi.sh: executing... 
[cont-init.d] unifi.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[22:06:48] INFO: Starting the UniFi Controller...
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f438761ae9e, pid=329, tid=0x00007f4384dc8700
#
# JRE version: OpenJDK Runtime Environment (8.0_275-b01) (build 1.8.0_275-8u275-b01-0ubuntu1~18.04-b01)
# Java VM: OpenJDK 64-Bit Server VM (25.275-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x668e9e]
#
# Core dump written. Default location: /run/s6/services/unifi/core or core.329
#
# An error report file with more information is saved as:
# /run/s6/services/unifi/hs_err_pid329.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
[22:06:56] INFO: Starting the UniFi Controller...
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000001400000005, pid=383, tid=0x00007fd5e1e0d700
#
# JRE version: OpenJDK Runtime Environment (8.0_275-b01) (build 1.8.0_275-8u275-b01-0ubuntu1~18.04-b01)
# Java VM: OpenJDK 64-Bit Server VM (25.275-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  0x0000001400000005
#
# Core dump written. Default location: /run/s6/services/unifi/core or core.383
#
# An error report file with more information is saved as:
# /run/s6/services/unifi/hs_err_pid383.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
[22:07:13] INFO: Starting the UniFi Controller...
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f1bb8db9ce9, pid=483, tid=0x00007f1b994f7700
#
# JRE version: OpenJDK Runtime Environment (8.0_275-b01) (build 1.8.0_275-8u275-b01-0ubuntu1~18.04-b01)
# Java VM: OpenJDK 64-Bit Server VM (25.275-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x842ce9]
#
# Core dump written. Default location: /run/s6/services/unifi/core or core.483
#
# An error report file with more information is saved as:
# /run/s6/services/unifi/hs_err_pid483.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
[22:07:19] INFO: Starting the UniFi Controller...
Exception in thread "launcher" java.lang.IllegalStateException: Tomcat failed to start up
	at com.ubnt.net.B.ö00000(Unknown Source)
	at com.ubnt.service.OoOO.øO0000(Unknown Source)
	at com.ubnt.ace.Launcher.main(Unknown Source)
Caused by: java.lang.RuntimeException: Web context failed to initialize
	... 3 more
</pre>

**Comment by archi071** [comment]
@frenck

sorry, I can't see the log.
I have restored with an image that I have as backup.
I have updated the adon 2 times, and I have not been able to restart the adon unify controller in either of the 2 times

has failed with the following
Add-on version:   0.20.1
 System: Home Assistant OS 5.10  (armv7 / raspberrypi3)
 Home Assistant Core: 2021.1.5
 Home Assistant Supervisor: 2021.01.7

**Comment by gerasimone** [comment]
@frenck
in my case the issue appeared after this steps
snapshot of hassio -> new installation -> restore of snapshot -> update unifi

**Comment by frenck** [comment]
In that case, I'll close up the issue. Not sure what the root cause was, but the configuration itself isn't managed by the add-on and out of control from this perspective.

@archi071 Your issue doesn't sound related at all, as this issue had a log. Please don't mix up different issues. Instead, create a separate issue.
