### ISSUE TITLE
Access to database via SSH

### ISSUE THREAD

**Issue by joeywheels** [hassio-addons/addon-unifi#159]
Is it possible to SSH into the unifi controller addon and change the default site?

The Ubiquiti wiki states that you need to configure the mongo database:
https://ubntwiki.com/guides/changing_the_default_site_in_unifi#:~:text=While%20it%20is%20not%20possible,site%20needs%20to%20be%20deleted

My problem is that I cannot find the addon folder via ssh or Samba. 

Is it possible to change the site name and/or remove the default in the configuration of the addon?

**Comment by sinclairpaul** [comment]
You can use the Portainer or SSH addons to docker exec into the container.  Please be aware none of this would be supported.
