### ISSUE TITLE
Don’t login after backup restore

### ISSUE THREAD

**Issue by italoc** [hassio-addons/addon-unifi#16]
I’m using hassio image on rpi2 with latest version of home assistant 0.84.6

I have exported the configuration from actual UniFi controller (another rpi with raspian) and imported in this add on, after import I can’t login in web infterface, always says username/password error

Another question, where is saved the configuration? I need to edit config.properties file

Thanks

**Comment by frenck** [comment]
I'm not able to reproduce the issue from your description.

you cannot edit the config.properties file in this add-on.
