### ISSUE TITLE
Cannot Connect to Set-up Wizard

### ISSUE THREAD

**Issue by markbw999** [hassio-addons/addon-unifi#162]
Hi,
I have installed the Unifi Addon and tried to follow the install instructions. The log look OK to me (no obvious errors) but when I click on Open Web UI it tries to connect to https://my-domain.duckdns.org:8443 but then fails to connect - I get ERR_CONNECTION_TIMED_OUT. My browser appears to think the page isn't secure but I don't know enough about SSL to fix it. Any suggestions on where to go next?
Thanks, Mark

**Comment by frenck** [comment]
Don't use an external address to configure this. Use: `http://<IP ADDRESS OF YOUR MACHINE>:8443` instead.

SSL warnings are common on local HTTPS applications.
