### ISSUE TITLE
Having trouble adopting devices with the hassio add on

### ISSUE THREAD

**Issue by Wheaties466** [hassio-addons/addon-unifi#166]
# Problem/Motivation

I am not able to provision specifically devices that do not have an ethernet port with the hassio add on of the unifi controller. I installed the controller on a windows computer and fired it up. It adopts and provisions right away.

The device I am having trouble provisioning is a beaconHD

## Expected behavior

I would expect to be able to provision a wireless device the same as a wired

## Actual behavior

the beaconHD never ends up provisioning.
## Steps to reproduce

Attempt to provision a beaconHD with a unifi controller add on running on Hassio. I have an existing flexhd as well that works and provisioned just fine.

## Proposed changes

I don't know how to fix this. I just wanted to make sure we are all aware of the problem as this is now the second time I have come across this.

**Comment by frenck** [comment]
Please read the add-on installation manual/documentation. As this is described.
