### ISSUE TITLE
Can´t adopt any device

### ISSUE THREAD

**Issue by luisrival** [hassio-addons/addon-unifi#168]
The adopting process never ends

![image](https://user-images.githubusercontent.com/8862466/110191265-0df7d900-7ded-11eb-8b1d-ec77b5ae6cb7.png)

Logs

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: UniFi Controller
 Manage your UniFi network using a web browser
-----------------------------------------------------------
 Add-on version: 0.20.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.12  (amd64 / intel-nuc)
 Home Assistant Core: 2021.3.2
 Home Assistant Supervisor: 2021.03.4
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] unifi.sh: executing... 
[cont-init.d] unifi.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[19:53:27] INFO: Starting the UniFi Controller...

Any idea?

**Comment by sinclairpaul** [comment]
Did you check the point 7 in the docs :wink:

**Comment by luisrival** [comment]
What I have to change? the hostname is the default and the ip is 192.168.1.8 the default that the DHCP assign

**Comment by luisrival** [comment]
Like this:

![image](https://user-images.githubusercontent.com/8862466/110191684-5f08cc80-7def-11eb-976c-a5f1edc4ff5b.png)

or I have to put the IP of hassio?

**Comment by luisrival** [comment]
Thanks after some minutes it is working!
