### ISSUE TITLE
No updates in over 2 months... Project dead?

### ISSUE THREAD

**Issue by EpicLPer** [hassio-addons/addon-unifi#17]
Seems like this project is dead...

**Comment by tjorim** [comment]
No, it's not dead at all. Do you have an actual issue with the add-on? It already has the latest unifi controller.

**Comment by ColinHarrington** [comment]
Do the images get rebuilt when a new version of Unifi is released?

**Comment by tjorim** [comment]
The version of unifi is pinned and if a new release is out, a dev will update it here and get it out.

**Comment by frenck** [comment]
No it is not dead :)
