### ISSUE TITLE
Unifi AddOn no longer starts

### ISSUE THREAD

**Issue by pedrams1** [hassio-addons/addon-unifi#171]
# Problem/Motivation

Unifi addon will no longer start, deleting the addon will fix the problem but restoring any backup recreates the issue. In the logs you see the following:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: UniFi Controller
 Manage your UniFi network using a web browser
-----------------------------------------------------------
 Add-on version: 0.20.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.12  (armv7 / raspberrypi3)
 Home Assistant Core: 2021.3.2
 Home Assistant Supervisor: 2021.03.4
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] unifi.sh: executing... 
Importing keystore /tmp/tmp.jYfqQT925C to /usr/lib/unifi/data/keystore...
Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore /usr/lib/unifi/data/keystore -destkeystore /usr/lib/unifi/data/keystore -deststoretype pkcs12".
[cont-init.d] unifi.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[02:00:50] INFO: Starting the UniFi Controller...
```
Nothing happens beyond this, the start-up sequence hangs indefinitely at this point.

If you attempt to access the HTTP port of the addon, the port is listening but the web server is not responsive:
```
$ nc -zv 192.168.1.2 8080
Connection to 192.168.1.2 8080 port [tcp/http-alt] succeeded!
```

The HTTPS port is not listening at all:
```
$ nc -zv 192.168.1.2 8443
nc: connect to 192.168.1.2 port 8443 (tcp) failed: Connection refused
```

Turning SSL on/off does not change the behaviour. The only way to restore the addon is to delete and start it again, and you will be greeted with the Unifi set up page. You can then list backups, but restoring any of them will put the addon in a broken state again.

## Expected behavior

UniFi add to restore backup, and start normally

## Actual behavior

Addon hangs after starting

## Steps to reproduce

Attempt to restore one of the problematic backups

**Comment by frenck** [comment]
The startup looks normal, and there is nothing in this PR description that I can work with / indicates a cause of the issue.

**Comment by pedrams1** [comment]
Thanks for the swift reply @frenck I can confirm this is a duplicate of https://github.com/hassio-addons/addon-unifi/issues/171 however with a slightly different manifestation in the logs. In this case, after restoring the backups the logs don't show errors, where they are some errors in the duplicate issue.

For completeness, this issue can be resolved by:

1. Taking the backup file from the filesystem of Hass `/backup/unifi`
2. Restoring the backup to a temporarily UniFi Controller installation outside of Hass/Addons
3. Performing a backup https://help.ui.com/hc/en-us/articles/204952144-UniFi-How-to-Create-and-Restore-a-Backup but selecting "Settings only"
4. Re-installing the Unifi Controller Addon and providing the "Settings only" back up file

On a side note, thank you for your efforts maintaining this project!

**Comment by bitcrumb** [comment]
@pedrams1 Which issue are you referring to as a duplicate (now you are linking to this exact issue)?

I am seeing the same behavior. After a fresh install of the add-on & restoring a backup, the Unifi Controller doesn't seem to start anymore. As stated by @pedrams1, removing the add-on and reinstalling resolves the issue of the Unifi Controller not starting. However, whenever I try to restore a backup, either via the initial setup of the Unifi Controller or via the settings, the software reports that the backup was applied and that it is restarting. After which the Unifi Controller never comes up again.

My logs are similar to that of @pedrams1:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: UniFi Controller
 Manage your UniFi network using a web browser
-----------------------------------------------------------
 Add-on version: 0.20.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.12  (armv7 / raspberrypi4)
 Home Assistant Core: 2021.3.4
 Home Assistant Supervisor: 2021.03.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] unifi.sh: executing... 
[cont-init.d] unifi.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:54:47] INFO: Starting the UniFi Controller...
```

I am seeing the same results when using netcat:

```
$ nc -zv 192.168.1.4 8080
Connection to 192.168.1.4 port 8080 [tcp/http-alt] succeeded!
```

and

```
$ nc -zv 192.168.1.2 8443
nc: connectx to 192.168.1.2 port 8443 (tcp) failed: Connection refused
```

I still have to try out the "settings only" workaround as provided above. I can't perform a [migration](https://help.ubnt.com/hc/en-us/articles/115002869188) from controller to controller (as referenced in the documentation of this add-on) since I only have one Raspberry  Pi 4 with HassOS on it.

My added thanks for your efforts & contributions!

**Comment by bitcrumb** [comment]
Update:
As suggested, the workaround to only upload a backup containing "settings only" seems to work.

So not sure if this issue has to do with the add-on or not :)

**Comment by crls00** [comment]
I just installed the add-on, it does not seem to start, the log shows starting but the UI never opens. I have no previous configuration. I just installed the add-on from scratch, nothing on the logs, even at Debug level.

```
Importing keystore /tmp/tmp.nAudfA7ux9 to /usr/lib/unifi/data/keystore...
Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore /usr/lib/unifi/data/keystore -destkeystore /usr/lib/unifi/data/keystore -deststoretype pkcs12".
[cont-init.d] unifi.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[00:12:51] INFO: Starting the UniFi Controller...
```

**Comment by pedrams1** [comment]
> @pedrams1 Which issue are you referring to as a duplicate (now you are linking to this exact issue)?

Apologies, the duplicate I was referring to is https://github.com/hassio-addons/addon-unifi/issues/115

I wonder if this is potentially a non-functional issue impacting the Pi? I just performed a restoration of a full back-up with the Hass AddOn running on an ODROID-N2+ and it worked without issue.

**Comment by sdeep211** [comment]
> I wonder if this is potentially a non-functional issue impacting the Pi? I just performed a restoration of a full back-up with the Hass AddOn running on an ODROID-N2+ and it worked without issue.

Can confirm that full restore worked on Hass OS on Proxmox VE.
Restore would not work on RPi4, this is a new issue for me, within last two weeks.
I was migrating away from the Pi anyway due to it's performance. Will also move

**Comment by gaborpro** [comment]
This happened to me as well. Mongodb in a bootloop. 

Could this be a new bug introduced in v6.1.71? Does mongodb require a special shutdown script to flush data?

**Comment by gaborpro** [comment]
It seems the settings only restore worked, thank you guys!
