### ISSUE TITLE
Not Adopting APs

### ISSUE THREAD

**Issue by JFK344** [hassio-addons/addon-unifi#172]
# Problem/Motivation

> After the Setup my controller wouldn't adopt any APs

## Expected behavior

> adopt the APs within ~5s

## Actual behavior
> When adopting it got stuck and sometimes switched to "disconnected"

## Steps to reproduce

> When the IP set in the controller Settings are set to the a wrong IP or Hostname (Docker IP) the APs cant connect correctly

## Proposed changes
Solution:
	1. Visit Unifi Controller webpage
	2. Got to Settings
	3. Switch to Classic View
	4. Select "cotroller"
	5. Under Controller Settings change:
		a. Controller Hostname/IP to the IP or Hostname of your HomeAssistant Server
		b. Select "Override inform host with controller hostname/IP
Apply changes!!

![image](https://user-images.githubusercontent.com/52662270/111027583-69c7f080-83f1-11eb-8b28-9db61e8fcbb6.png)

**Comment by frenck** [comment]
As documented in the installation instructions, which you obviously have read 😜

**Comment by JFK344** [comment]
Obviously….Sorry totally my mistake.  Sent from Mail for Windows 10 From: Franck NijhofSent: Saturday, 13 March 2021 13:02To: hassio-addons/addon-unifiCc: JFK344; AuthorSubject: Re: [hassio-addons/addon-unifi] Not Adopting APs (#172) As documented in the installation instructions, which you obviously have read 😜—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
