### ISSUE TITLE
missing log file?

### ISSUE THREAD

**Issue by dedepene** [hassio-addons/addon-unifi#176]
# Problem/Motivation

The server.log file is missing in /usr/lib/unifi/logs as [per this](https://help.ui.com/hc/en-us/articles/204959834-UniFi-How-to-View-Log-Files). All I see is mongod.log.
## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)
```
root@a0d7b954-unifi:/usr/lib/unifi/logs# ls -la
total 15276
drwxr-xr-x 3 root root     4096 Feb 12 09:56 .
drwxr-xr-x 1 root root     4096 Feb 12 09:56 ..
-rw-r--r-- 1 root root 15626211 Mar 24 10:12 mongod.log
drwxr-xr-x 2 root root     4096 Feb 12 09:56 remote
```
## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Log output is redirected to the output file descriptor of the docker process. Besides, it doesn't matter, as there should not be any reason do go into add-on containers.

**Comment by dedepene** [comment]
@frenck I do need the log to try and troubleshoot an issue i'm having with one particular AP that's dropping all of my IoT devices, shows them as connected with 60% experience score, but Esphome clearly reports them all as disconnected.. Where do I find the output file descriptor of the docker process please? Thanks!

**Comment by frenck** [comment]
In the add-on logs in the Home Assistant frontend.

**Comment by dedepene** [comment]
> In the add-on logs in the Home Assistant frontend.

This log is completely empty, always has been. Not a single character.

![image](https://user-images.githubusercontent.com/6883390/112435202-19378800-8d4d-11eb-8c7e-bf4cbce8cfed.png)

**Comment by frenck** [comment]
That seems like a bug with HA or your setup. Even if there was an issue with the logs from UniFi, those logs cannot be empty.

**Comment by dedepene** [comment]
> That seems like a bug with HA or your setup. Even if there was an issue with the logs from UniFi, those logs cannot be empty.

Should I open a separate issue for this then?
