### ISSUE TITLE
Unifi Cloud not working - DNS issues with controller container

### ISSUE THREAD

**Issue by shbatm** [hassio-addons/addon-unifi#18]
# Problem/Motivation

I am unable to connect this controller to my UBNT cloud account; I keep getting error messages that it is unable to reach the cloud.  When I check the controller logs, I get several errors that all seem to revolve around failed DNS lookups including failure to find firmware updates for my devices.

Running bash inside the container on the host, I can see that the only DNS entry in `/etc/resolv.conf` is for Docker (my other Docker dns settings from `/etc/docker/daemon.json` are not copied in.  `ping` and `nslookup` are not installed inside the container, so I can't do any further tests.

## Expected behavior

DNS name resolution to function.

## Actual behavior

Unable to perform any DNS lookups from Controller container.

## Steps to reproduce

Try to connect a cloud account to the Unifi Controller running in this container.

## Proposed changes

Possible to change `config.json` to allow `host_network: true`? I don't know if this would fix the issue or not. I don't have this problem in the Hass.io container or any other addons.  I tried to build my own version of this addon from the Dockerfile, but kept having issues on my `aarch64` system (Rock Pi 4b).

**Comment by frenck** [comment]
> Running bash inside the container on the host, I can see that the only DNS entry in /etc/resolv.conf is for Docker (my other Docker dns settings from /etc/docker/daemon.json are not copied in. 

That is expected, since Hass.io is taking care of that.

Sounds like you are using the adguard, dnsmasq or pi-hole add-on, without setting a static IP, including external DNS on the host system

**Comment by shbatm** [comment]
Nope, no other DNS controllers setup (still could be a problem with my setup). And it only seems to be an issue with this Docker container, everything else doesn't have an issue with name resolution including my existing Unifi container on this same device (Linuxserver.io image, host network false). 

And to be clear, this is not resolution of the Unifi controller, this is the unifi controller unable to resolve any sites (e.g. Ubnt.com).  I'll grab a snapshot of the error next time I get a chance to take down my existing controller container and retry this one.

**Comment by gdiciancia** [comment]
Dear Frenck, Is it possible that below setting is causing the problem? I was running a Unifi (jacobalberty/unifi:latest) on the same server, but as 'host', and cloud was working.
- Setting: "host_network": false
Thank you Frenck for the last update, it did fix the hung startup. Now just Cloud is open for me :)

**Comment by frenck** [comment]
I actually use 2 instances of this add-on with the cloud option... so not sure why that is an issue for you guys.

**Comment by BostonMikeGetHub** [comment]
I tried it again with the 0.5.0 version and got the same issue as before including the java warning. When I get the time,  I'm going to try to migrate my old pi uniFi controller to a Windows Base controller to see if it is a migration issue. I'll let you know if that works or not.
________________________________

**Comment by frenck** [comment]
No response in almost a month, closing issue.
