### ISSUE TITLE
Supervisor crashes with add-on and hassio not accessible anymore

### ISSUE THREAD

**Issue by CmKeen** [hassio-addons/addon-unifi#188]
# Problem/Motivation

> Whenever I start the add-on, the supervisor stops responding and the whole home assistant becomes unaccessible anymore, wether via SSH or web ui

## Expected behavior

Should not crash

## Actual behavior

> (What actually happened)

## Steps to reproduce

Fresh install of homeassistant os. Only add-ons installed are SSH and file editor.
Then, install of unifi controller and start it.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by Shamshala** [comment]
Is it right after you start the Unifi addon when your HA stops working or is it after, for instance, reboot of your host?

Because something just crashed my HA after reboot (basically no errors from Core or Supervisor, webinterface not unaccessible) and i wasn't even able to recover it via latest snapshot (same result). So i recovered the system via snapshot of the entire drive (which was significantly older) and updated each thing one by one, except Unifi addon, and it seems like everything is ok now.

**Comment by CmKeen** [comment]
It is whenever the add-on is running. If I install everything with or
without the add-on, it goes fine. As soon as the add-on is started, it’s
pure luck. I can get it running for a few minutes or it silently crashes
immediately. The thing is that I have no indication whatsoever, I just have
no access to the web interface or the app.

Since then, I did some additional tests and found out that it mostly
crashes with the 64bit version. With the 32bit, it seems to work but is
highly unresponsive.
I now have a 32bit version installed but not started and my whole setup is
working fine.

Olivier

On 28 April 2021 at 17:26:46, Shamshala ***@***.***) wrote:

Is it right after you start the Unifi addon when your HA stops working or
is it after, for instance, reboot of your host?

Because something just crashed my HA after reboot (basically no errors from
Core or Supervisor, webinterface not unaccessible) and i wasn't even able
to recover it via latest snapshot (same result). So i recovered the system
via snapshot of the entire drive (which was significantly older) and
updated each thing one by one, except Unifi addon, and it seems like
everything is ok now.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/hassio-addons/addon-unifi/issues/188#issuecomment-828548654>,
or unsubscribe

**Comment by matteskonto** [comment]
I have the same issue, with version 0.21 and 0.22 if I restart the AddOn the supervisor crashes and also I cannot access the host from ssh after some hours. I cannot access the web-interface also during this time.

A reboot fixes the issue but I have to stop the addon after the reboot or else it will crash again.

**Comment by BitTourette** [comment]
same here
