### ISSUE TITLE
Error processing element InMemoryAppender ([Appenders: null]): CLASS_NOT_FOUND

### ISSUE THREAD

**Issue by WTFoX74** [hassio-addons/addon-unifi#189]
# Problem/Motivation

I have UniFi controller running for quite a while now on hassio, it ran perfect, until 4am last night. My controller went offline. I am running UniFi 0.21 on hassio core-2021.4.6 and supervisor-2021.04.0.

When starting the UniFi controller I do see this message in the log of the add-on:

```
[17:41:45] INFO: Starting the UniFi Controller...
2021-04-25 17:41:51,980 main ERROR Error processing element InMemoryAppender ([Appenders: null]): CLASS_NOT_FOUND
2021-04-25 17:41:54,599 main ERROR Unable to locate appender "InMemoryAppender" for logger config "root"
```

## Expected behavior

No errors and a Unifi online controller

## Actual behavior

Unifi controller is stuck during launch and remains offline

## Steps to reproduce

Simply stop and start the Unifi Controller

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by WTFoX74** [comment]
I have UniFi controller running for quite a while now on hassio, it ran perfect, until 4am last night. My controller went offline. I am running UniFi 0.21 on hassio core-2021.4.6 and supervisor-2021.04.0.

When starting the UniFi controller I do see this message in the log of the add-on:

Copy to clipboard
[17:41:45] INFO: Starting the UniFi Controller...
2021-04-25 17:41:51,980 main ERROR Error processing element InMemoryAppender ([Appenders: null]): CLASS_NOT_FOUND
2021-04-25 17:41:54,599 main ERROR Unable to locate appender "InMemoryAppender" for logger config "root"
After this the controller seems to be stuck and does not continue (UniFi controller remains offline). I rebooted hassio couple of times (cold and hard boot), I restored a backup of a week ago, but nothing helps.

Help would be much appreciated. Thanks!

**Comment by cromulus** [comment]
I'm having the same experience. Of note, the add-on is using 10% of ram (400MB) and 9% CPU even though it's not functional.

**Comment by chrislader** [comment]
Same failure here, Hopefully a fix will be introduced soon. I cannot access anything of the unifi webui...

**Comment by glyph-se** [comment]
This errors showing in the logs is a known problem upstream. Though it shouldn't affect the normal operation of the addon. See https://github.com/hassio-addons/addon-unifi/issues/180#issuecomment-814298918

**Comment by PrathikGopal** [comment]
Same here, guess we will have to wait till 6.2.x..

**Comment by spiderwolf27** [comment]
I'm having the same problem as well. I've noticed that memory was on 0, I've changed those to memory max: 2048 and memory init: 512 as the example states. But still no succes.
I found a solution on [https://community.ui.com/questions/Error-on-startup-of-Unifi-Controller-on-Raspberry-Pi-Error-processing-element-InMemoryAppender/4ed28ed2-fa98-4d7a-b242-80a4100b7529#answer/80bfee48-49a0-48e5-9c9c-090b112a51fa](url) but I don't see an option how to execute this on Hass.io

Is this probably a fix, while waiting for an update?

**Comment by PrathikGopal** [comment]
Heard its a docker issue, 6.2.0 didn't solve it.

**Comment by xanderdekok** [comment]
Just upgraded to 0.22.0 from 0.21.0 on my raspberry pi 4.
0.21.0 was running fine. After installing 0.22.0 I get the same error. 

Any idea how to get the controller to work again?

**Comment by chrisuk-web** [comment]
Having the same issue running 0.22 on a raspberry pi 4 and can see the comment about the 6.2.23 upgrade. This is a little new to me - does this mean that there will be a new version of the Unify Controller add on that's currently at version 0.22 that will reference the 6.2.23 software?

**Comment by frenck** [comment]
@chrisuk-web See the release notes.
