### ISSUE TITLE
Version 6.1.71 has bug in hotspot manager

### ISSUE THREAD

**Issue by stijn-dhondt** [hassio-addons/addon-unifi#196]
# Problem/Motivation

> as statet in topic Hotspot manager is not working

## Expected behavior

> update Unifi controller to at least 6.2.17
see article: https://community.ui.com/questions/Unifi-Controller-6-1-71-no-hotspot-manager/8a5e1baa-499d-4fe6-915e-ce282acad044 

## Actual behavior

> Hotspot manager not available anymore Bug has been resolved by Ubiquity

## Steps to reproduce

> Use current version 6.1.71

## Proposed changes

>update Unifi controller to at least 6.2.17
see article: https://community.ui.com/questions/Unifi-Controller-6-1-71-no-hotspot-manager/8a5e1baa-499d-4fe6-915e-ce282acad044

**Comment by kamil996** [comment]
I can confirm. Also there is a problem with device disconnecting on 6.171
> https://community.ui.com/questions/Devices-constantly-reconnecting-after-controller-upgrade-to-6-1-71/275f5c3a-7a78-4314-9524-4c856b9190dc
