### ISSUE TITLE
Tomcat Crashes on launch.

### ISSUE THREAD

**Issue by cromulus** [hassio-addons/addon-unifi#206]
# Problem/Motivation

Add-on fails to start

## Expected behavior

I expect the add on to launch.

## Actual behavior

This error occurs:
```[17:52:00] INFO: Starting the UniFi Controller...
Exception in thread "launcher" java.lang.IllegalStateException: Tomcat failed to start up
	at com.ubnt.net.B.ö00000(Unknown Source)
	at com.ubnt.service.C.Óo0000(Unknown Source)
	at com.ubnt.ace.Launcher.main(Unknown Source)
Caused by: java.lang.RuntimeException: Web context failed to initialize
	... 3 more
```
## Steps to reproduce

 Add-on version: 0.23.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.13  (armv7 / raspberrypi4)
 Home Assistant Core: 2021.5.4
 Home Assistant Supervisor: 2021.04.3

I believe simply upgrading to the latest version of the add-on causes the problem.

**Comment by cromulus** [comment]
Reverting to 0.22.0 fixes the problem, and the add-on boots.

**Comment by sanderpleijers** [comment]
Same here, i had to restore a snapshot to do that. Even with a blanco 0.23 installation, you cannot import the .unf config exported from the previous 0.22 controller. Any way to fix this?

**Comment by ahostn** [comment]
Why is this critical error not fixed in (now) 22 days?? I don’t need any workarounds, I can just go and install standalone unifi server if this won’t be fixed.

**Comment by cromulus** [comment]
Because Home Assistant is a free, opensource project?

seriously, the community that creates and maintains HA has put incredible amounts of work into it and it is the best opensource platform for home automation out there.

If running a UniFi controller instance is so crucially important for you, then, yes, spin up a separate instance. 

If you must run your UniFi inside Hassio then dig in, setup a development environment, and try to figure out what is causing the error, fix it and submit a PR. Or wait for someone else to do the same.
