### ISSUE TITLE
PEM file not found.

### ISSUE THREAD

**Issue by xel-arjona** [hassio-addons/addon-unifi#21]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
If you even can't do the effort of typing a proper message... well... I'll take some effort to close the issue.
