### ISSUE TITLE
Unable to do initial setup of controller !

### ISSUE THREAD

**Issue by vincegre** [hassio-addons/addon-unifi#222]
# Problem/Motivation

Installed the plugin in HA on PI4. Went without problem and it starts also but can't get initial setup of controller to work as UI is unable to accept my UI credentials. I have even changed the pass of my account in ui.com and then updated it in the UI of the controller but always complains invalid username or pass ! Looks like it can't access Internet...

## Expected behavior

Initial wizard to go seamlessly

## Actual behavior

Can't use controller as can't finish initial wizard and no way to escape it !

## Steps to reproduce

Not sure how to reproduce the problem. Could only test with 2 different ui.com accounts and same exact problem ! Nothing shows up in log of plugin in ha :(

**Comment by DellProSupportGse** [comment]
Keep getting "There was a problem logging into your account, please try again later." Any solution for this?

**Comment by vincegre** [comment]
> Keep getting "There was a problem logging into your account, please try again later." Any solution for this?

Have you been able to do initial setup of controler ? here problem solved with an update of the integration :D

**Comment by DellProSupportGse** [comment]
I am on step 3 of 7 on the Web UI. How to I get the updated integration?

**Comment by vincegre** [comment]
> I am on step 3 of 7 on the Web UI. How to I get the updated integration?

What are you talking about ?? The integration with HA has no direct link with the Unifi controller add-on itself !!
