### ISSUE TITLE
Upgrade controller to 6.2.26

### ISSUE THREAD

**Issue by ulic75** [hassio-addons/addon-unifi#231]
# Problem/Motivation

I have an existing controller running v6.2.26 that I would like to migrate to run on my Home Assistant instance and it won't import into v6.2.25.

## Proposed changes

Rev'n the version number in the Dockerfile.  https://community.ui.com/releases/UniFi-Network-Application-6-2-26/0dfcbc77-8a4f-4e20-bb93-07bbb0237e3a is now listed as Official.

This is a pretty simple change but I'd be happy to submit a PR.

**Comment by frenck** [comment]
Hi there, but this is an issue tracker, not a feature request form.

Thanks for understanding 👍

**Comment by ulic75** [comment]
Perhaps the CONTRIBUTING.md should be updated.  I was simply trying to follow the suggestion prior to submitting a PR.

> When contributing to this repository, please first discuss the change you wish to make via issue, email, or any other method with the owners of this repository before making a change.

**Comment by frenck** [comment]
Thanks 👍 

Updates will land when ready, its not a feature or something. All add-ons gets updates on a regular schedule and when they are tested.
