### ISSUE TITLE
SSL issue with upgrade to 0.23.2

### ISSUE THREAD

**Issue by Kev1000000** [hassio-addons/addon-unifi#235]
# Problem/Motivation

> After upgrading to 0.23.2, I no longer can login to the web UI, with Chrome (and other browsers) showing this error: ERR_SSL_VERSION_OR_CIPHER_MISMATCH

## Expected behavior

> To be able to login via SSL with a Lets Encrypt cert provided by the DuckDNS add on.

## Actual behavior

> I receive this error: ERR_SSL_VERSION_OR_CIPHER_MISMATCH

## Steps to reproduce

> Simply try launching the web UI.  I did restore my snapshot to 0.23.1 and it also now throws the same error, so even downgrading to an older version does not work anymore.

**Comment by collse** [comment]
https://github.com/hassio-addons/addon-unifi/issues/205#issuecomment-883456091

**Comment by Kev1000000** [comment]
Yep, can confirm that the following steps resolve this issues temporarily by disabling SSL.

- Uninstall the UniFi add-on
- Re-install the UnFi add-on
- Make sure to DISABLE SSL before starting the add-on
- Start the add on.
- Restore any backups to the UniFi controller that is stored in /backup/unifi

Note, this won't actually solve the issue of using a Let's Encrypt cert, but it will at least allow you to get things running again in the short term.

**Comment by yltsa** [comment]
I have the same issue.. but I removed the backups just before reading this page.

**Comment by tuanha2000vn** [comment]
I have the same issue, it was working for few days now the error look like this. 

```
This site can’t provide a secure connection
home.duckdns.org uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
Unsupported protocol
The client and server don't support a common SSL protocol version or cipher suite.
```

**Comment by yltsa** [comment]
I uninstalled DuckDNS, but it did not help.

**Comment by garyak** [comment]
Updated to the latest HAOS and ran into this also: `SSL_ERROR_NO_CYPHER_OVERLAP` on Firefox and Chrome.

**Comment by Dominic-070** [comment]
Same over here: ERR_SSL_VERSION_OR_CIPHER_MISMATCH

**Comment by mpoli** [comment]
Same problem here. I migrated to Home Assistant Blue and right after updating to 0.23.2:

On Chrome:
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

On the Core Log:
ERROR (MainThread) [homeassistant.components.unifi] Error connecting to the UniFi controller at localhost: Error requesting data from localhost: Cannot connect to host localhost:8443 ssl:default [[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1129)]

**Comment by garyak** [comment]
See the 2021.7 release note for breaking change related to NGINX. The error you cite is expected and can be ignored as described in the UniFi add-on documentation. The suggestion to remove, reinstall, configure to not use SSL, then restart worked for me as well.

**Comment by askusbloodfist** [comment]
I dont se how losing a funktion and removing a funktion is sen a working as intended? So are we just to live with that ssl funktion dont work as it did? Then why have it at all. Or What is the sulution to get it working….

**Comment by garyak** [comment]
Wait for the add-on developer to correct the problem and release an update.
