### ISSUE TITLE
Documentation still says 32 bit supported

### ISSUE THREAD

**Issue by e28eta** [hassio-addons/addon-unifi#251]
I see that #242 drops support for 32-bit systems, but I see at least a couple places (in the README and DOCS, possibly others?) that say something like: this add-on supports all Home Assistant supported architectures, including the Raspberry Pi.

I'm not sure how you'd like to update that line, so I'm simply filing an issue instead of a PR with a suggested fix.

**Comment by frenck** [comment]
A Raspberry Pi can run 64-bits.

**Comment by nljuggler** [comment]
> A Raspberry Pi can run 64-bits.

I'm not that much of a infra kinda guy...

Can I just upgrade my current installation or do I need to re-install everything on upgrading to 64-bit?

**Comment by bitcrumb** [comment]
@nljuggler AFAIK you have to download a new HA OS image (64 bit) version. Makes sure you performed a full HA backup. After flashing the new image onto the SD card of your Pi, you can than upload the backup on the setup screen of Home Assistant.

If you have a more custom setup (e.g. no HA OS), you'll have to perform other backups/reinstalls as well yourself.
