### ISSUE TITLE
Removed 23.2 and installed fresh 1.0.0 but browser won't open the page

### ISSUE THREAD

**Issue by danielbrunt57** [hassio-addons/addon-unifi#252]
I had the same trouble as others have reported with the upgrade from 23.2 to 1.00 and read the other posts so I restored my snapshot, created & downloaded a backup in Unifi, uninstalled 23.2 and installed 1.0.0 fresh but I have the following errors when Edge or Chrome try to open https://brunt.duckdns.org:8443
Edge:
![image](https://user-images.githubusercontent.com/49846893/129667096-223abfd1-0e5a-4a14-91e1-ce4ce4a622a8.png)
Chrome:
![image](https://user-images.githubusercontent.com/49846893/129667453-7b2e2a38-a538-450a-a267-29ba6fe3e1b7.png)

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: UniFi Controller
 Manage your UniFi network using a web browser
-----------------------------------------------------------
 Add-on version: 1.0.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.2  (aarch64 / odroid-n2)
 Home Assistant Core: 2021.8.7
 Home Assistant Supervisor: 2021.06.8
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] unifi.sh: executing... 
[cont-init.d] unifi.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[22:07:10] INFO: Starting the UniFi Controller...
```

**Comment by danielbrunt57** [comment]
I've just installed Firefox and tried that...
![image](https://user-images.githubusercontent.com/49846893/129667995-062d2c33-8c44-4e94-8c5c-82a2acaecace.png)

**Comment by danielbrunt57** [comment]
Backup restored and up and running but only with Firefox; I still see the same errors in Edge and Chrome.

**Comment by danielbrunt57** [comment]
Let me know how I can help...

**Comment by membersound** [comment]
The trick is to export your unifi settings from within the controller app, then uninstall the unifi addon, reinstall it and restore the settings from within the controller:

- Uninstall Unifi Addon
- Restore Partial Backup of old 0.23.x Unifi Addon
- Login into Unifi and export settings
- Uninstall Unifi Addon (this is important!)
- Restart 
- Fresh install the unifi addon 1.0.0
- restore exported settings

**Comment by danielbrunt57** [comment]
I have done those steps and have access to Unifi via my browsers using https://unifi.brunt.local which resolves to 192.168.1.104 but the Open Web UI button takes me to https://brunt.duckdns.org, which also resolves to 192.168.1.104 on my LAN but the page via that URL fails to load...
![image](https://user-images.githubusercontent.com/49846893/129792316-377309c8-eb31-477a-89e9-fb096fc5bc5b.png)
![image](https://user-images.githubusercontent.com/49846893/129792242-2d46b99a-639c-4338-8681-a2da0937bc1e.png)

**Comment by danielbrunt57** [comment]
Since Firefox was working but not Chrome or Edge, I researched HSTS...
In Chrome, I went to chrome://net-internals/#hsts and deleted domain brunt.duckdns.org - problem solved.
In Edge, I went to Settings>Privacy, search and services>Clear Browsing Data and chose Cached images and files - problem solved.

**Comment by danielbrunt57** [comment]
I dug deeper into the issue and have disabled HSTS in NGINX and now I can get to UniFi via the OPEN WEB UI button.
I changed from:
```
hsts: max-age=31536000; includeSubDomains
```
to:
```
hsts: max-age=0
```
