### ISSUE TITLE
snapshot' is deprecated, 'backup' should be used instead. Please report this to the maintainer of UniFi Controller

### ISSUE THREAD

**Issue by paarak** [hassio-addons/addon-unifi#263]
Fresh install Home Assistant OS 6.2, core-2021.8.8, supervisor-2021.08.1.

appears in supervisor log 

### Error i logsnapshot' is deprecated, 'backup' should be used instead. Please report this to the maintainer of UniFi Controller

[supervisor log.txt](https://github.com/hassio-addons/addon-unifi/files/7096234/supervisor.log.txt)

**Comment by At-M** [comment]
this issue still persists, it's still coming up in the homeassistant supervisor log, even if the unifi controller isn't installed.


21-10-03 00:11:45 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot' is deprecated, 'backup' should be used instead. Please report this to the maintainer of UniFi Controller

**Comment by fufar** [comment]
pls fix it

**Comment by modem** [comment]
I'm getting this warning even though I don't have it installed. Fix is expected.

**Comment by FrankBurmo** [comment]
Please fix this!

**Comment by frfstu** [comment]
![Screenshot_20211021-015438](https://user-images.githubusercontent.com/87616721/138184042-3266f79c-ddd6-4c69-8f36-9e9142c90a7d.png)
