### ISSUE TITLE
Wrong IP address

### ISSUE THREAD

**Issue by michalterbert** [hassio-addons/addon-unifi#27]
# Problem/Motivation

Wrong IP address in case of adoption a new device. Used addon on RPi 3+ and hass.io.

## Expected behavior

Should be Home Assistant IP address not docker container ip

## Actual behavior
```
IP Address of docker container:
UBNT-BZ.v4.0.21# info
Model:       UAP-AC-LR
Version:     4.0.21.9965
MAC Address: 18:xx:xx:xx:xx:xx
IP Address:  10.0.0.253
Hostname:    UBNT
Uptime:      268 seconds

Status:      Unknown[11] (http://172.30.33.2:8080/inform)
```
## Steps to reproduce

Run addon with default configuration, try addopt new device

## Proposed changes

Change internal docker container ip to supervisior ip.

**Comment by frenck** [comment]
Please read the manual again:

https://github.com/hassio-addons/addon-unifi#installation
