### ISSUE TITLE
Solving the dilemma of config.gateway.json

### ISSUE THREAD

**Issue by aweingarten** [hassio-addons/addon-unifi#271]
# Problem/Motivation
Yet another user who was blocked by config.gateway.json not being accessible. Could not set static DNS records without access to this file.  

I was able to get unblocked by roughly doing
1. Setting up HA host for SSH:  https://developers.home-assistant.io/docs/operating-system/debugging/
2. SSH into HA host `ssh root@homeassistant.local -p 22222`
3. `docker -ps`  to get the name of the unifi container
4. Get into the docker container `docker exec -it addon_<somehash>_unifi sh`
5. `apt-get update`
6. `apt-get install nano`
7.  `pico /usr/lib/unifi/data/sites/default/config.gateway.json`

This is pretty rough for most people.  I was wondering if we could collaborate and come up with a better approach for folks.  I tried to research the different attempts of dealing with this.  I know that this has been discussed in the past without much success:

- https://github.com/hassio-addons/addon-unifi/issues/216
- https://github.com/hassio-addons/addon-unifi/pull/148
- https://github.com/hassio-addons/addon-unifi/issues/122
- https://github.com/hassio-addons/addon-unifi/pull/38
- https://github.com/hassio-addons/addon-unifi/issues/35
- https://github.com/hassio-addons/addon-unifi/issues/12

# Failed Approached:
- There is no SSH daemon on the container.  Installing one seems complicated.  
- Hacking the backup directory linking to instead link to `/usr/lib/unifi/data/sites`

# Proposed Approach
Map `/usr/lib/unifi/data/` inside the container to `addons/unifi/data` in ha.  In theory this should not break snapshotting.  I am happy to PR this if we can nail down an approach that works for the maintainer.

**Comment by frenck** [comment]
See all other issues linked and closed for reasoning
