### ISSUE TITLE
Support Ingress

### ISSUE THREAD

**Issue by Gregable** [hassio-addons/addon-unifi#276]
# Problem/Motivation

UniFi Controller runs a web server on port 8443. There is no user/pass/2factor authentication for this server, so it's not secure to expose the port to the internet. It also isn't set up for serving an HTTPS cert as far as I can tell.

## Expected behavior

If I understand correctly, the [ingress feature](https://www.home-assistant.io/blog/2019/04/15/hassio-ingress/) would solve this problem.

## Proposed changes

Support the [ingress feature](https://www.home-assistant.io/blog/2019/04/15/hassio-ingress/).

**Comment by sinclairpaul** [comment]
https://github.com/hassio-addons/addon-unifi/blob/main/unifi/DOCS.md#known-issues-and-limitations

As stated in the documentation, it cannot be supported.

If you really want external based access to your internal network, I would suggest exploring the Unifi offerings.

**Comment by Gregable** [comment]
Thanks for the follow up. That's unfortunate.
