### ISSUE TITLE
2FA implementation timeline

### ISSUE THREAD

**Issue by quantummobile** [hassio-addons/addon-unifi#280]
# Problem/Motivation

There is no support for 2FA in unifi addon at the moment. 
Do you plan to add 2FA support and if you do - what is the timeline for that? 
> (Why the issue was filed)

## Expected behavior

2FA support in unifi addon.
> (What you expected to happen)

## Actual behavior

Integration fails to connect to unifi controller because of 2FA is enabled for the controller.
> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This is the repository of the add-on, this is not an integration. Add-ons and integrations are not the same thing, thus you have submitted an unrelated issue.
