### ISSUE TITLE
Devices going into adopting state every day

### ISSUE THREAD

**Issue by krzysiek2788** [hassio-addons/addon-unifi#286]
# Problem/Motivation

> (Why the issue was filed)

After update to 1.0.0 my uniFi devices going into adopting state almost every day and I need to manual adopt via ssh

## Expected behavior

> (What you expected to happen)
Devices stayed connected to the controller

## Actual behavior

> (What actually happened)
Almost every day I need to adopt via ssh

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by Naesstrom** [comment]
Is that why my devices are looking like this?
![image](https://user-images.githubusercontent.com/6575206/135719168-0084b728-c305-4fda-9cba-f247e3ff6af0.png)

**Comment by krzysiek2788** [comment]
Most probably yes you have the same issue and need to adopt manually via ssh

**Comment by soleen** [comment]
I think I am also seeing this problem:
![Screenshot 2021-10-21 9 30 33 AM](https://user-images.githubusercontent.com/9452992/138288304-e02ed1b1-4be3-4ca2-8ff9-68899cd009b2.png)
Any suggestion on what more data is needed in order to root cause this issue?

**Comment by frenck** [comment]
1.1.0 version of the add-on is released, with an update to the UniFi Network Application. Could you try again?

**Comment by krzysiek2788** [comment]
I can confirm that new version and solution to override hostname like @thomasverhaeghe mentioned solved my issue.
