### ISSUE TITLE
Error creating Java Virtual Machine after upgrade to 1.0.0

### ISSUE THREAD

**Issue by olli-dot-dev** [hassio-addons/addon-unifi#289]
I just moved my whole system from 32 to 64-bit as I wanted to upgrade the Unifi Addon to 1.0.0 and other stuffs. Everything else works like a charme running 64-bit. I then did the Unifi addon update to 1.0.0

The addon pretends to be running an even shows some cpu-usage but is not reachable.

I changed the loglevel to trace and can now see the following errors/messages:

`[08:15:55] INFO: Starting the UniFi Controller...
[08:15:55] TRACE: bashio::config.has_value: memory_max
[08:15:55] TRACE: bashio::config: memory_max
[08:15:55] TRACE: bashio::jq: /data/options.json if (.memory_max == null) then
            null
        elif (.memory_max | type == "string") then
            .memory_max // empty
        elif (.memory_max | type == "boolean") then
            .memory_max // false
        elif (.memory_max | type == "array") then
            if (.memory_max == []) then
                empty
            else
                .memory_max[]
            end
        elif (.memory_max | type == "object") then
            if (.memory_max == {}) then
                empty
            else
                .memory_max
            end
        else
            .memory_max
        end
[08:15:55] TRACE: bashio::var.has_value: 0
[08:15:55] TRACE: bashio::config: memory_max
[08:15:55] TRACE: bashio::jq: /data/options.json if (.memory_max == null) then
            null
        elif (.memory_max | type == "string") then
            .memory_max // empty
        elif (.memory_max | type == "boolean") then
            .memory_max // false
        elif (.memory_max | type == "array") then
            if (.memory_max == []) then
                empty
            else
                .memory_max[]
            end
        elif (.memory_max | type == "object") then
            if (.memory_max == {}) then
                empty
            else
                .memory_max
            end
        else
            .memory_max
        end
[08:15:55] TRACE: bashio::config.has_value: memory_init
[08:15:55] TRACE: bashio::config: memory_init
[08:15:55] TRACE: bashio::jq: /data/options.json if (.memory_init == null) then
            null
        elif (.memory_init | type == "string") then
            .memory_init // empty
        elif (.memory_init | type == "boolean") then
            .memory_init // false
        elif (.memory_init | type == "array") then
            if (.memory_init == []) then
                empty
            else
                .memory_init[]
            end
        elif (.memory_init | type == "object") then
            if (.memory_init == {}) then
                empty
            else
                .memory_init
            end
        else
            .memory_init
        end
[08:15:55] TRACE: bashio::var.has_value: 0
[08:15:55] TRACE: bashio::config: memory_init
[08:15:55] TRACE: bashio::jq: /data/options.json if (.memory_init == null) then
            null
        elif (.memory_init | type == "string") then
            .memory_init // empty
        elif (.memory_init | type == "boolean") then
            .memory_init // false
        elif (.memory_init | type == "array") then
            if (.memory_init == []) then
                empty
            else
                .memory_init[]
            end
        elif (.memory_init | type == "object") then
            if (.memory_init == {}) then
                empty
            else
                .memory_init
            end
        else
            .memory_init
        end
Invalid maximum heap size: -Xmx0m
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.`

I tried playing around with Max Memory and Initial Memory but neither did help and the addon keeps exiting with the fatal exception of not being able to create the Java Virtual Machine.

As soon as I change the values for Max Memory and Initial Memory, the trace-log only tells me the following:

`[14:03:17] TRACE: bashio::fs.file_exists: /data/unifi/data/system.properties
[14:03:17] TRACE: bashio::fs.file_exists: /usr/lib/unifi/data/keystore
[14:03:17] TRACE: bashio::fs.file_exists: /data/keystore_reset
[cont-init.d] unifi.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:03:17] INFO: Starting the UniFi Controller...
[14:03:17] TRACE: bashio::config.has_value: memory_max
[14:03:17] TRACE: bashio::config: memory_max
[14:03:17] TRACE: bashio::jq: /data/options.json if (.memory_max == null) then
            null
        elif (.memory_max | type == "string") then
            .memory_max // empty
        elif (.memory_max | type == "boolean") then
            .memory_max // false
        elif (.memory_max | type == "array") then
            if (.memory_max == []) then
                empty
            else
                .memory_max[]
            end
        elif (.memory_max | type == "object") then
            if (.memory_max == {}) then
                empty
            else
                .memory_max
            end
        else
            .memory_max
        end
[14:03:17] TRACE: bashio::var.has_value: 2048
[14:03:17] TRACE: bashio::config: memory_max
[14:03:17] TRACE: bashio::jq: /data/options.json if (.memory_max == null) then
            null
        elif (.memory_max | type == "string") then
            .memory_max // empty
        elif (.memory_max | type == "boolean") then
            .memory_max // false
        elif (.memory_max | type == "array") then
            if (.memory_max == []) then
                empty
            else
                .memory_max[]
            end
        elif (.memory_max | type == "object") then
            if (.memory_max == {}) then
                empty
            else
                .memory_max
            end
        else
            .memory_max
        end
[14:03:17] TRACE: bashio::config.has_value: memory_init
[14:03:17] TRACE: bashio::config: memory_init
[14:03:17] TRACE: bashio::jq: /data/options.json if (.memory_init == null) then
            null
        elif (.memory_init | type == "string") then
            .memory_init // empty
        elif (.memory_init | type == "boolean") then
            .memory_init // false
        elif (.memory_init | type == "array") then
            if (.memory_init == []) then
                empty
            else
                .memory_init[]
            end
        elif (.memory_init | type == "object") then
            if (.memory_init == {}) then
                empty
            else
                .memory_init
            end
        else
            .memory_init
        end
[14:03:17] TRACE: bashio::var.has_value: 512
[14:03:17] TRACE: bashio::config: memory_init
[14:03:17] TRACE: bashio::jq: /data/options.json if (.memory_init == null) then
            null
        elif (.memory_init | type == "string") then
            .memory_init // empty
        elif (.memory_init | type == "boolean") then
            .memory_init // false
        elif (.memory_init | type == "array") then
            if (.memory_init == []) then
                empty
            else
                .memory_init[]
            end
        elif (.memory_init | type == "object") then
            if (.memory_init == {}) then
                empty
            else
                .memory_init
            end
        else
            .memory_init
        end`

I've waited then for more than 60 minutes and still nothing happens (no further log-entires nore the start of the controller).

**Comment by frenck** [comment]
`Invalid maximum heap size: -Xmx0m`

Sounds like a configuration gone bad? Please reset the add-on configuration to the defaults and try again.

**Comment by olli-dot-dev** [comment]
I meanwhile had rolled back to the 32bit version... After your response I again updated to 1.1.0. As of now, my controller remains on the status "Database Migration in progress...". It's been in this state for at least 45 minutes by now and nothing seems to be changing.

The log says the following
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: UniFi Network Application
 Manage your UniFi network using a web browser
-----------------------------------------------------------
 Add-on version: 1.1.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.6  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.11.2
 Home Assistant Supervisor: 2021.10.8
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] unifi.sh: executing... 
[cont-init.d] unifi.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[19:28:48] INFO: Now starting the UniFi Network Application...
[19:28:48] INFO: Note: No add-on specific logs beyond this point.`

**Comment by sinclairpaul** [comment]
There were specific challenges in upgrading the Mongo Version in the move to the 1.x release (essentially I believe the original storage engine used no longer runs on ARM).

The only workaround you can do is to restore the actual Controller backup (the UNF file located in Backup/Unifi), on a fresh install of the updated addon.

You could of course rollback to take the backup prior.

**Comment by olli-dot-dev** [comment]
Thanks @sinclairpaul , I followed your advice and did a fresh re-install of version 1.1.0 with a backup-file. Everything is working fine now!
