### ISSUE TITLE
Update of the Unifi Controller version

### ISSUE THREAD

**Issue by diegole81** [hassio-addons/addon-unifi#290]
# Problem/Motivation

> I would like to restore a controller backup done on a controller with version 6.4.54 but this is not possible because the controller version I get with the add-on is older (version 6.2.26).

## Expected behavior

> I would like to update the controller version to the latest one released by ubiquiti to proceed with the migration.

## Actual behavior

> The migration does not work because the add-on controller has an older version.

## Steps to reproduce

> Try to restore a backup done on Unifi Controller version 6.4.54 to the add-on controller (version 6.2.26).

## Proposed changes

> It would be good if the add-on controller version would be updated more often or if the documentation would describe the procedure to update the controller version to the latest one available.

**Comment by frenck** [comment]
This is a feature request, not a bug.
