### ISSUE TITLE
Conflict over port 1900?

### ISSUE THREAD

**Issue by ggravlingen** [hassio-addons/addon-unifi#3]
# Problem/Motivation

I have discovered an interesting behaviour with my Raspberry Pi 3. I'm running the Unifi addon, the deCONZ addon and the Airsonos addon. If I start deCONZ and Airsonos and then start Unifi, Unufi won't start. If I start Unifi first and then the other two, it works like a charm.

I think I've been able to trace the error to port 1900 (PnP?) and a conflict over the port then Unifi starts.

## Expected behavior

I'm expecting all the addons to start, regardless of what order they start in.

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Yep, that happens.
You got to change or disable the port on either of those add-ons. A port cannot be used twice, that is a limit of how networking works.

If you'd like to disable a port; just make it empty.
