### ISSUE TITLE
Addon unable to restore backup - stuck at starting

### ISSUE THREAD

**Issue by FlashyDuck** [hassio-addons/addon-unifi#30]
# Problem/Motivation
This issue seems related to https://github.com/hassio-addons/addon-unifi/issues/11 but this problem has returned? I'm unable to restore a backup. This results in a broken addon. Stopping/starting or Uninstalling/Installing don't work. I had to restore a full snapshot for the addon to work again.

## Expected behavior
Start addon
Restore backup 
Restart addon
Business as usual.

## Actual behavior
Start addon
Restore backup
Restarting addon
-Stuck- 
"Starting addon" and "Repairing database" message continue, even after 12 hours.

## Steps to reproduce
Run Hassio on RPI3
Install Unifi addon
Start Unifi addon
Choose to restore backup
And you get - Stuck -

Logs don't reveal anything:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: UniFi Controller
 Manage your UniFi network using a web browser
-----------------------------------------------------------
 Add-on version: 0.8.0
 You are running the latest version of this add-on.
 System: HassOS 1.10  (armv7 / raspberrypi3)
 Home Assistant version: 0.91.0
 Supervisor version: 152
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in e.g, GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to DEBUG
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 50-persist-data.sh: executing... 
[cont-init.d] 50-persist-data.sh: exited 0.
[cont-init.d] 51-db.sh: executing... 
[cont-init.d] 51-db.sh: exited 0.
[cont-init.d] 60-ssl.sh: executing... 
[cont-init.d] 60-ssl.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:53:21] INFO: Starting the UniFi Controller..
```
Only solution seems to be to restore a backup of hassio to make unifi addon work again and start from scratch. 

## Proposed changes
I have no clue. Tried to look true the previous topics, but the solution for this seems to be needing some handy work from @frenck 

EDIT

Found a work around and will describe the steps I took.
- Install full snapshot
- Start and open Unifi after hassio re-install
- Go back and stop Unifi and delete
- Install Unifi again
- Go true the setup process (do not restore backup in setup process!)
- Access Unifi and go to Maintenance and choose to restore backup

Trying to restore in the setup process or from an older install (so the one that's re-installed with the full snapshot of Hassio) won't work. You need the Unifi addon in a "clean state" sort of speak, only than I was able to succesfully restore a backup of Unifi.

EDIT 2

Still, cloud access won't enable for some reason. This worked in the beginning, but somehow after disabling/enabling it once, it hasn't worked since. That was the main reason for me to try and restore a backup. So maybe this is related to the failing restore backup part? I'm don't seem to be blocking stuff. Tried a different account etc, but I may be going off topic. Just wanted to give the information in case it's helpfull. 
`There was an error registering credentials. Unable to connect to UniFi cloud. Please check your network connection, and try again.`

EDIT 3
Found a message in the controller log pointing to IPS. I disabled IPS, provisioned and rebooted hassio (and thus the controller). This seems to have fixed the Cloud Access problem. 

My theory: Enabling IPS blocks not only Cloud Access (no wonder it's in beta), but it also brakes something which prevents restoring a backup. I haven't found anything that can explain that, but maybe this rings a bell and helps the development of this addon.

Really great addon! Thank you!

**Comment by frenck** [comment]
From the add-on point of view, there is not much going on here.
The add-on simply wraps existing software and starts it :S
