### ISSUE TITLE
HTTP Status 404 – Not Found

### ISSUE THREAD

**Issue by Kitser** [hassio-addons/addon-unifi#302]
I'm running version  1.0.0 and can't access the webui. When I go to https://192.168.80.200:8443/ I get 
HTTP Status 404 – Not Found.
![2021-11-05 14_32_13-Instellingen](https://user-images.githubusercontent.com/46002263/140518293-00d97373-3236-4a89-a1f2-2c6108d74fbd.png)

This is in the addon log:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
 Add-on: UniFi Controller
 Manage your UniFi network using a web browser

 Add-on version: 1.0.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.6  (amd64 / qemux86-64)
 Home Assistant Core: 2021.11.0
 Home Assistant Supervisor: 2021.10.8

 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.


[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to FATAL
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] unifi.sh: executing... 
[cont-init.d] unifi.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Exception in thread "launcher" java.lang.IllegalStateException: Tomcat failed to start up
	at com.ubnt.net.B.if(Unknown Source)
	at com.ubnt.service.ooOO.Óo0000(Unknown Source)
	at com.ubnt.ace.Launcher.main(Unknown Source)
Caused by: java.lang.RuntimeException: Web context failed to initialize
	... 3 more
```

And in the system log I get

```
21-11-04 18:41:49 WARNING (MainThread) [supervisor.addons.options] Option 'ssl' does not exist in the schema for UniFi Controller (a0d7b954_unifi)
21-11-04 18:41:49 WARNING (MainThread) [supervisor.addons.options] Option 'certfile' does not exist in the schema for UniFi Controller (a0d7b954_unifi)
21-11-04 18:41:49 WARNING (MainThread) [supervisor.addons.options] Option 'keyfile' does not exist in the schema for UniFi Controller (a0d7b954_unifi)
21-11-04 18:41:49 WARNING (SyncWorker_0) [supervisor.addons.options] Option 'ssl' does not exist in the schema for UniFi Controller (a0d7b954_unifi)
21-11-04 18:41:49 WARNING (SyncWorker_0) [supervisor.addons.options] Option 'certfile' does not exist in the schema for UniFi Controller (a0d7b954_unifi)
21-11-04 18:41:49 WARNING (SyncWorker_0) [supervisor.addons.options] Option 'keyfile' does not exist in the schema for UniFi Controller (a0d7b954_unifi)
```

I saw a few other topics according to this problem. And they reverted back to v0.23.2 (https://github.com/hassio-addons/addon-unifi/releases/tag/v0.23.2)
But I just saw this problem only just today and my Home Assistant snapshots with v0.23.2 are already overwritten.
From what I am understanding this has to do with the 32bit version of Home Assistant. 
As far as I know, I'm running 64bit OS. I've installed Home Assistant as a VM on my Proxmox OS with the script of whiskerz007.

This in config/info:

## System Health

version | core-2021.11.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.75
arch | x86_64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4872
Installed Version | 1.12.4
Stage | running
Available Repositories | 958
Installed Repositories | 19

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | November 12, 2021, 1:00 AM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-west-2-2.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.6
-- | --
update_channel | stable
supervisor_version | supervisor-2021.10.8
docker_version | 20.10.8
disk_total | 68.2 GB
disk_used | 49.3 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), ADB - Android Debug Bridge (0.8.0), AdGuard Home (4.1.9), Assistant Relay (0.7.4), Bitwarden (Vaultwarden) (0.12.0), DahuaVTO2MQTT (1.0.14), Duck DNS (1.12.5), ESPHome (1.19.4), File editor (5.3.2), Glances (0.12.2), Grafana (7.0.2), Hass.io Google Drive Backup (0.97.4), InfluxDB (4.1.1), MariaDB (2.4.0), Mosquitto broker (6.0.1), Nginx Proxy Manager (0.11.0), Node-RED (9.2.0), Terminal & SSH (9.1.3), WireGuard (0.5.1), Z-Wave JS (0.1.45), motionEye (0.15.0), Visual Studio Code (3.6.2), UniFi Controller (1.0.0), Portainer (2.0.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 25
views | 15
mode | storage

</details>

@frenck How can I restore the Unifi addon on my system?
Thanks in advance!

**Comment by Kitser** [comment]
I've found an old snapshot of Home Assistant. So I was able to downgrade to 0.23.0.
But when I update to 1.0.0 I the same problem occurs. 
There are 3 breaking changes:

**Drop support for 32-bits systems (armv7, i386)**
But as shown above I'm running x86_64

**Use cold backups**
This could not cause the above problem as far I can tell.

 **Drop support for custom SSL certificates**
I don't use a custom SSL certificate. This is my config:
![2021-11-05 14_23_02-Supervisor - Home Assistant](https://user-images.githubusercontent.com/46002263/140517032-95afaaeb-d85b-4745-a926-40aca7c8ad0c.png)

So what do I need to do to upgrade to 1.0.0?

**Comment by frenck** [comment]
This should be fixed with the 1.1.0 release

**Comment by Kitser** [comment]
Thanks for the hard work, Frenck

**Comment by Drewskieza** [comment]
My version 1.0.0 was working but after upgrading to 1.1.0 now I get the above error
