### ISSUE TITLE
Database Migration in Progress

### ISSUE THREAD

**Issue by worldwidefelix** [hassio-addons/addon-unifi#314]
What happened to my Unifi controller? It is showing message "Database Migration in Progress"
more than 2hrs.

Is it normal situation for upgrading from 0.23.2 to 1.1.0?

**Comment by sinclairpaul** [comment]
Assuming you are running under an arm setup (it would be great if you could post addon logs and config), please make sure you have a UNF backup (by default under backup/unifi), uninstall the addon the restore the backup within the application.

You can see multiple discussions in previous logged issues.
