### ISSUE TITLE
Plugin yet maintained ??

### ISSUE THREAD

**Issue by vincegre** [hassio-addons/addon-unifi#320]
# Problem/Motivation

Unable to run the plugin since quite a while and now that it's in version 1 it generates a lot of errors in HA logs and Web GUI of Unifi controller displays all the time: Database migration in Process, and nothing else !

## Expected behavior

Be able to access/use the Unifi controller through its web interface

## Actual behavior

Generates lot of errors in HA logs each time I try to access the web UI of Unifi controler:

```
21-12-11 08:43:29 WARNING (MainThread) [supervisor.addons.options] Option 'ssl' does not exist in the schema for UniFi Network Application (a0d7b954_unifi)
21-12-11 08:43:29 WARNING (MainThread) [supervisor.addons.options] Option 'certfile' does not exist in the schema for UniFi Network Application (a0d7b954_unifi)
21-12-11 08:43:29 WARNING (MainThread) [supervisor.addons.options] Option 'keyfile' does not exist in the schema for UniFi Network Application (a0d7b954_unifi)
```

## Steps to reproduce

Install the plugin in hassio and run it

## Proposed changes

No clue how to fix it :(

Thanks

Vincèn

**Comment by AlecRust** [comment]
Sounds like you upgraded from 0.x to 1.x. Have you tried a fresh installation of 1.x?

https://github.com/hassio-addons/addon-unifi/issues/316#issuecomment-978072067

**Comment by frenck** [comment]
These have been dropped in the v1.0.0 release:

<https://github.com/hassio-addons/addon-unifi/releases/tag/v1.0.0>

It seems like you add-on configuration, however, still have them. Remove them from your configuration.
