### ISSUE TITLE
Re-authenticate after restart

### ISSUE THREAD

**Issue by Drewskieza** [hassio-addons/addon-unifi#324]
# Problem/Motivation

Every time I reboot (updates, power failures, etc.) HA I have to re-authenticate with this add-on, which also means I have to restart HA after fixing it for my entities to show (may not need this but I am not a patient man).  I believe this only started with 1.1.1 but may be wrong.

## Expected behavior

Should not need to re-authenticate.

## Actual behavior

After restart I have to re-authenticate

## Steps to reproduce

Reboot HA device

**Comment by dragosde** [comment]
Curious about this too. Out of all my addons this is the only one asking for authentication after I reboot the host.

**Comment by adamfeldman** [comment]
I think the UniFi controller clears session after any restart. I run a hardware controller outside HA and I always have to login again.

**Comment by adamfeldman** [comment]
The UniFi controller also doesn't integrate with HA authentication, it uses its own.

**Comment by Drewskieza** [comment]
> I think the UniFi controller clears session after any restart. I run a hardware controller outside HA and I always have to login again.

I agree with logging into the controller frontend again but I have to re-authenticate my integration and that does not seem correct.  As far as I can remember this only started recently, 1 or 2 versions ago.  it was not like this in the past.

This may be due to a change on the UniFi side or me missing something but it does mean if we have a power failure my integration based on UniFi are broken till I reauthenticate. This causes an issue with automations based on presence derived from devices connected to UniFi (Wi-Fi) as this info does not pass to HA.

**Comment by adamfeldman** [comment]
Ah, thank you for clarifying. I don’t use the HA integration for UniFi –
that might also be tracked on the GitHub repo for HA core, instead of this
addon.

**Comment by Drewskieza** [comment]
Thanks, I think you are correct, thanks for pointing me in the right direction, I have logged the issue on that side and believe this issue can be closed.

https://github.com/home-assistant/core/issues/61963
