### ISSUE TITLE
Unifi version in latest release is marked as incorrect version

### ISSUE THREAD

**Issue by pieterbos** [hassio-addons/addon-unifi#329]
# Problem/Motivation

Both the commit message (#328 ) and the release notes say the latest version updates the unifi controller to 6.5.5. it is actually 6.5.55
Since 6.5.5 is old and probably vulnerable to log4shell, this is not so nice.

## Expected behavior

The release notes to be updated to say version 6.5.5

**Comment by frenck** [comment]
Stuff happens. I cannot change history as it has already been distributed.
