### ISSUE TITLE
Devices not Adopting post HASSIO updates

### ISSUE THREAD

**Issue by brycecampbell** [hassio-addons/addon-unifi#333]
# Problem/Motivation

Upon updating home assistant components (core/supervisor), the Unifi Add-on will not re-adopt the devices - But under "Events" it does show as "adopted"
But its not and cannot manage the UniFi devices.

## Expected behavior

Clients are suppose to show as adopted and be able to be managed from UniFi

## Actual behavior

shows as "readopting" 

Had this before - resetting the entire site did fix it, but don't want to do that each and everytime
![unifi clients](https://user-images.githubusercontent.com/31030102/148468044-c7ae1716-fcd4-40f9-9fb3-a1689a3de2e5.jpg)
![unifi events](https://user-images.githubusercontent.com/31030102/148468048-e489ddce-7c54-48b8-bb45-876130271073.jpg)

**Comment by sinclairpaul** [comment]
Have you set the inform address correctly, I believe it's under System, Application Configuration.

**Comment by brycecampbell** [comment]
I did find the Application Configuration - the address was there and correct. 

But "Override inform host with the UniFi OS Console’s hostname/IP." was unchecked (as recall always has been) - I enabled that and it seems to be adopting now.

**Comment by sinclairpaul** [comment]
Cool, lets close this out for now, I believe it's likely just config, and not related to updates (more the addon restart)

**Comment by brycecampbell** [comment]
Sounds good - thanks!
