### ISSUE TITLE
Controller cannot adopt the devices

### ISSUE THREAD

**Issue by Aalleexx-87** [hassio-addons/addon-unifi#338]
Hi, here is the logs of the add-on.

<img width="726" alt="149306603-c062e292-4268-48ff-b1a9-9a19dbf22ae8" src="https://user-images.githubusercontent.com/52315680/149377249-6dafebf6-34fb-4d22-932c-ee5bd47c9ce4.png">

I can't understand where is the problem but the result is that in the controller there devices are always in status of "adopting". I've tried to forget and re-adopt the devices but nothing happens.

Thanks

**Comment by AlecRust** [comment]
Are you getting this after upgrading to 1.1.4?

My APs weren't adopted after the update, but after rebooting the host they are.

**Comment by Aalleexx-87** [comment]
> Are you getting this after upgrading to 1.1.4?
> 
> 
> 
> My APs weren't adopted after the update, but after rebooting the host they are.

I've never used it before today..I had it on my Pc

**Comment by jodasm** [comment]
I’ve got the same issue.
Tried multiple times now to adopt devices however they keep staying in the “adopting” status.

I have another UniFi Network application  installed on a pc that doesn’t have this issue.

**Comment by iMicknl** [comment]
@Aalleexx-87 / @jodasm did you send the 'Host for Inform' correctly? You need to Override the Inform Host as mentioned in the documentation; https://github.com/hassio-addons/addon-unifi/blob/main/unifi/DOCS.md.

**Comment by Aalleexx-87** [comment]
@iMicknl thank you so much! Now everything is working!

**Comment by jodasm** [comment]
> @Aalleexx-87 / @jodasm did you send the 'Host for Inform' correctly? You need to Override the Inform Host as mentioned in the documentation; https://github.com/hassio-addons/addon-unifi/blob/main/unifi/DOCS.md.

Oops.  Ok I skimmed over that bit.
It's now working fine thank you.
