### ISSUE TITLE
UI unreachable on 0.23.2 version

### ISSUE THREAD

**Issue by golddragon007** [hassio-addons/addon-unifi#339]
# Problem/Motivation

Once it happened that I was not able to reach anymore the Unify UI and the HA integration also broke. When I tried to open the Unify UI, I've receiving `ERR_SSL_VERSION_OR_CIPHER_MISMATCH` in chrome. As well as in other browsers. I do use HTTPS on HA and several other integrations, where this problem does not occur.
I'm not able to upgrade to 64x so reinstalling the addon is not an option.

If I restart the addon, then it won't find at all host (`ERR_CONNECTION_REFUSED`) then after a long time, it will turn back to `ERR_SSL_VERSION_OR_CIPHER_MISMATCH`.

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: UniFi Controller
 Manage your UniFi network using a web browser
-----------------------------------------------------------
 Add-on version: 0.23.2
 There is an update available for this add-on!
 Latest add-on version: 1.1.4
 Please consider upgrading as soon as possible.
 System: Raspbian GNU/Linux 10 (buster)  (armv7 / raspberrypi4)
 Home Assistant Core: 2021.12.7
 Home Assistant Supervisor: 2021.12.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] unifi.sh: executing... 
Importing keystore /tmp/tmp.LPup8vnGdP to /usr/lib/unifi/data/keystore...
Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore /usr/lib/unifi/data/keystore -destkeystore /usr/lib/unifi/data/keystore -deststoretype pkcs12".
[cont-init.d] unifi.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:52:21] INFO: Starting the UniFi Controller...
```

Why it's not available?

## Expected behavior

Load the UI and be able to connect the HA integration to the addon.

## Actual behavior

Receiving ERR_SSL_VERSION_OR_CIPHER_MISMATCH message.

## Steps to reproduce

Unknown.

**Comment by sinclairpaul** [comment]
If you use a custom certificate you may want to disable it and use the self-signed one, however the only path forward for you is to move to the 64-bit version as this will no longer be maintained.

**Comment by golddragon007** [comment]
I use let's encrypt cert.

**Comment by golddragon007** [comment]
And there's no stable 64-bit version of Rasberry os yet.

**Comment by sinclairpaul** [comment]
Raspbian/Raspberry PI OS isn't a supported platform for Home Assistant, but that is outside the scope of this addon.
