### ISSUE TITLE
Can't find the addon

### ISSUE THREAD

**Issue by pezlin** [hassio-addons/addon-unifi#341]
The add-on is not to be found in add-on store. I am running Home assistant os 7.1, supervisor 2021.12.2 and Core 2021.12.9.

**Comment by frenck** [comment]
Your installation might mis the community store, you can add it using this button:

[![Open your Home Assistant instance and show the add add-on repository dialog with a specific repository URL pre-filled.](https://my.home-assistant.io/badges/supervisor_add_addon_repository.svg)](https://my.home-assistant.io/redirect/supervisor_add_addon_repository/?repository_url=https%3A%2F%2Fgithub.com%2Fhassio-addons%2Frepository)
