### ISSUE TITLE
Processor usage is all time high due to the unifi addon.

### ISSUE THREAD

**Issue by worldwidefelix** [hassio-addons/addon-unifi#342]
After recent update, cpu usage got around 97% all day.

![image](https://user-images.githubusercontent.com/59109996/149842708-72ac602d-bc06-4bf4-978c-c60c01deb717.png)

![image](https://user-images.githubusercontent.com/59109996/149842836-06d823bb-9048-4238-a25a-f3b134cb077e.png)

![image](https://user-images.githubusercontent.com/59109996/149842855-6590f2f4-b740-4ebd-be2b-9aed7d0c5f5d.png)

**Comment by timknowlden** [comment]
Also had this issue and it overheated my pi which in turn was smoking after installing this add on.

**Comment by Ir0nhid3** [comment]
I've been experiencing that issue since I've updated to the newest version (2.0.0). Nothing else changed so far.

**Comment by 2Crazy187** [comment]
> There hasn't been any activity on this issue recently, so we clean up some of the older and inactive issues. Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by leaving a comment 👍 This issue has now been marked as stale and will be closed if no further activity occurs. Thanks!

I've the same issue. I'm on the latest version of Home Assistant and Unifi controller. What are the best settings for CPU and Ram for an RPI 3B?

**Comment by MBakerSE** [comment]
I still have the same problem. It doesn't happen immediately after starting the add-on but once it happens CPU remains high. Just now CPU for the add-on had been at 85% for over 90 minutes before I stopped it.
Host Operating System	Home Assistant OS 7.6
Version	core-2022.5.1
Raspberry Pi 4

**Comment by salopette** [comment]
Same Problem

<html>
<body>


Version | core-2022.5.2
-- | --
Installationstyp | Home Assistant OS
Entwicklung | false
Supervisor | true
Docker | true
Benutzer | root
Virtuelle Umgebung | false
Python-Version | 3.9.9
Betriebssystemfamilie | Linux
Betriebssystem-Version | 5.10.108
CPU-Architektur | x86_64
Zeitzone | Europe/Berlin


</body>
</html>

![sshot-1](https://user-images.githubusercontent.com/32480002/167259221-060b4dab-4069-463b-8b2b-a5338401edf3.jpg)
