### ISSUE TITLE
Home Assistant Unifi Addon has empty topology

### ISSUE THREAD

**Issue by chrisuk-web** [hassio-addons/addon-unifi#344]
# Problem/Motivation

Addon is 1.1.4, but this has happened on some previous versions. Core is core-2021.12.9

Host Operating System | Home Assistant OS 7.1
-- | --
Update Channel | beta
Supervisor Version | supervisor-2021.12.2
Docker Version | 20.10.9
Disk Total | 109.3 GB
Disk Used | 24.7 GB
Healthy | true
Supported | true
Board | rpi4-64

## Expected behavior

Topology to show two access points and circa 50 devices

## Actual behavior

![Screenshot 2022-01-26 231926](https://user-images.githubusercontent.com/81539509/151263416-d852284a-3728-4327-a396-a4dd21eed7e2.png)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
I doubt there is anything to be done here from the addon perspective (the addon just runs the Unifi software), I would suggest looking for help with Ubiquiti themselves.

**Comment by chrisuk-web** [comment]
Thanks.
