### ISSUE TITLE
:0 webRtcId 1 terminated with code: (-2147090409) WebRTC connection interrupted from far side

### ISSUE THREAD

**Issue by salopette** [hassio-addons/addon-unifi#346]
# Problem/Motivation

Current version: 1.1.4
## Expected behavior

> (What you expected to happen)

Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] unifi.sh: executing... 
[cont-init.d] unifi.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:08:02] INFO: Now starting the UniFi Network Application...
[13:08:02] INFO: Note: No add-on specific logs beyond this point.
:0 TCP candidates not supported yet
:0 TCP candidates not supported yet
:0 TCP candidates not supported yet
:0 Permanent error code on channel bind request: 403 - Forbidden IP
:0 All TURN channel bindings failed
:0 SSL_read permanently failed: (6) 
:0 Unable to do SSL I/O
:0 webRtcId 1 terminated with code: (-2147090409) WebRTC connection interrupted from far side
> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Please post the full addon startup log, it looks like it is failing to bind.

**Comment by salopette** [comment]
I have now activated debug in the settings and restarted.
now there are no more errors.
I will watch and write!

**Comment by salopette** [comment]
Now I have errors in the log again.


-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to DEBUG
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] unifi.sh: executing... 
[cont-init.d] unifi.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:08:24] INFO: Now starting the UniFi Network Application...
[09:08:24] INFO: Note: No add-on specific logs beyond this point.
:0 TCP candidates not supported yet
:0 TCP candidates not supported yet
:0 TCP candidates not supported yet
:0 Permanent error code on channel bind request: 403 - Forbidden IP
:0 TCP candidates not supported yet
:0 TCP candidates not supported yet
:0 TCP candidates not supported yet
:0 All TURN channel bindings failed
:0 Permanent error code on channel bind request: 403 - Forbidden IP
:0 SSL_read permanently failed: (6) 
:0 Unable to do SSL I/O
:0 webRtcId 1 terminated with code: (-2147090409) WebRTC connection interrupted from far side
:0 STUN id:   4; fd: 286 172.30.33.2:47724 -> 10.136.97.20:41736 (eth0) DTLS id: 0 () (PEER) timed out
:0 STUN id:   5; fd: 286 172.30.33.2:47724 -> 46.114.137.20:36705 (eth0) DTLS id: 0 () (PEER) timed out
:0 STUN id:   6; fd: 286 172.30.33.2:47724 -> 46.114.137.20:48181 (eth0) DTLS id: 0 () (PEER) timed out
:0 All TURN channel bindings failed
