### ISSUE TITLE
Migrating from an existing controller - UBNT link invalid

### ISSUE THREAD

**Issue by Function-10** [hassio-addons/addon-unifi#348]
# Problem/Motivation

This link ( https://help.ubnt.com/hc/en-us/articles/115002869188 ) is no longer valid & available to the public

## Expected behavior

Open KB article for migrating from one Unifi controller to a new one

## Actual behavior

Unifi web sites requests a log in * then states access denied error message

## Steps to reproduce

1. Click on link to view article
2. Wait for Unifi site to load, redirect & log in
3. Receive access denied error

## Proposed changes

- Find link to current publicly available KB article & update link in the documentation

**Comment by sinclairpaul** [comment]
In all honesty we should probably just remove the link/section, as it's a challenge to maintain.

**Comment by Function-10** [comment]
Maybe just put in a generic blurb to find the migration documentation on the UBNT support web site?
