### ISSUE TITLE
config.gateway.json

### ISSUE THREAD

**Issue by DarrenRatcliffe** [hassio-addons/addon-unifi#35]
# Problem/Motivation

It is often required that you need to create a gateway config json file and store it within the directory structure of the unifi controller to be read. The contents of the json file vary from implementation to implementation

## Expected behavior

Save json file to "wherever_your_controller_is_installed_directory\Ubiquiti UniFi\data"

## Actual behavior

No documented way of doing this

## Steps to reproduce

none

## Proposed changes

Is it possible to ssh in to the docker container running the Unifi controller add-on?

**Comment by almostserious** [comment]
There seems to be the "hacky" way of doing a partial backup, unpacking the addon, adding the config. Repacking and restoring. It would be great if the folder \data\unifi\data\sites\default could be made accessible in the same way as the backups.

**Comment by almostserious** [comment]
I added the code required for the advanced configuration (a symbolic link in a new folder @ /config/unifi in a branch.

**Comment by DarrenRatcliffe** [comment]
I can only see the master branch, will this be merged in to master at some point?

**Comment by almostserious** [comment]
Im totally new to GIT... i dont really know how this works yet. Here is the link to the branch where i changed the file. I think in order to get it merged i first need the approval of the author on this thread before im allowed to make a pull request.

https://github.com/almostserious/addon-unifi/tree/patch-1

**Comment by DarrenRatcliffe** [comment]
Check with @frenck but I think if you were to make a pull request he would then review it

**Comment by sinclairpaul** [comment]
@almostserious You can just create a Pull Request, it will need to be approved before merging and would be reviewed.  Just as an initial comment, have you considered how users upgrading from a previous version would be affected?

**Comment by frenck** [comment]
More important, what is your site is not "default"....

**Comment by almostserious** [comment]
Understood. I adjusted the symbolic link to also use the backup folder ( because of snapshots) /backup/unifi/config and linked to the sites in general. In this case the user can choose which site they want to configure if they are not using the default.
