### ISSUE TITLE
upgrade controller version to UniFi Network Application 7.0.25

### ISSUE THREAD

**Issue by andreimoraru** [hassio-addons/addon-unifi#357]
# Problem/Motivation
Upgrade to the UniFi Network Application 7.0.25

> (Why the issue was filed)
A new release of the UniFi Network Application
https://community.ui.com/releases/UniFi-Network-Application-7-0-25/3344c362-7da5-4ecd-a403-3b47520e3c01

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes
To upgrade the controller version to latest one
> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
No need to open issues for that, as it's not an issue but a wish/feature request.
