### ISSUE TITLE
Device or the operating system  not compatible

### ISSUE THREAD

**Issue by designerferro** [hassio-addons/addon-unifi#359]
# Problem/Motivation
Addon shows message "This add-on is not compatible with the processor of your device or the operating system you have installed on your device." in my Linux raspberrypi 5.10.63-v7l+ #1457 SMP Tue Sep 28 11:26:14 BST 2021 armv7l GNU/Linux.

Running Home-assistant at RPi4 in Docker. 

## System Health

version | core-2022.4.7
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.63-v7l+
arch | armv7l
timezone | Europe/Lisbon

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.24.5
Stage | running
Available Repositories | 1027
Downloaded Repositories | 12

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Raspbian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | supervisor-2022.04.0
docker_version | 20.10.8
disk_total | 58.3 GB
disk_used | 22.1 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.14.0), Dnsmasq (1.4.4), Plex Media Server (2.8.0), File editor (5.3.3), Portainer (2.0.0), ESPHome (2022.3.1), AdGuard Home (4.5.1), Mosquitto broker (6.0.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 8
views | 10
mode | storage

</details>

## Expected behavior
Addon was expected to installl and work, but shows it self as unavailable at /hassio/store.

I've installed it directly worked, but would rather have the addon version intalled: 
`$ wget https://dl.ui.com/unifi/7.0.25/unifi_sysvinit_all.deb; 
sudo dpkg -i unifi_sysvinit_all.deb; sudo apt install -f -y; 
sudo /usr/lib/unifi/bin/unifi.init stop; 
java --version; 
sudo apt-get install openjdk-8-jdk;  sudo /usr/lib/unifi/bin/unifi.init start`

It was expected to either say the requirementes it didn't comply with or install the docker image as expected, but i couldn't find any information in the forums or the add on that would help me understand what is wrong.

## Steps to reproduce

Install Home-assistant in a RPi4 for armv7 (32bit) and check

## Proposed changes

It seems Unifi works. Maybe it has something to do with the OpenJDK running in the docker image?

**Comment by designerferro** [comment]
To the @hassio-addons team: thanks for the great job!

**Comment by sinclairpaul** [comment]
As per the docs:
![image](https://user-images.githubusercontent.com/24625998/165190760-63459ce9-f79a-4bed-a752-3e57b7993ef7.png)
You need a 64-bit OS

**Comment by designerferro** [comment]
I understand that I need 64-bit os to use the add on. I don’t understand why is that I need a 64-bit OS to use the add on since the software works fine in 32-bit OS. Is it the OpenJDK requirement?

**Comment by sinclairpaul** [comment]
32 bit support was removed due to the increased maintenance costs, mainly around Mongo under Alpine if I recall.  You can always run your own version under a 32 bit OS, but it isn't something this project will support/manage.
