### ISSUE TITLE
Non legacy UI is not including WiFi 3 (802.11g) devices in device count or showing their WiFi band

### ISSUE THREAD

**Issue by chrisuk-web** [hassio-addons/addon-unifi#360]
# Problem/Motivation

I have some 802.11g devices (with name "wlan0") that have a WiFi band of dash in my UI:

![image](https://user-images.githubusercontent.com/81539509/166574927-81aac28a-c468-4f7b-80e9-70824808cc4f.png)

The dashboard doesn't show them either, or include them in the device count on that page:

![image](https://user-images.githubusercontent.com/81539509/166574987-4d64ffc4-bfe7-4911-9590-09749be041cb.png)

However, if I switch to legacy mode I can see these WiFi 3 devices listed as 11g:

![image](https://user-images.githubusercontent.com/81539509/166575061-2edb8802-9f4a-491c-942d-9814b1b5486a.png)

If I use the iOS app I can see the number of WiFi 3 devices and the device count is correct:

![image](https://user-images.githubusercontent.com/81539509/166574877-e4738ea8-d5c9-445f-9f48-378dff2658c4.png)

## Expected behavior

WiFi 3 devices to feature in non legacy UI

## Actual behavior

As above

## Steps to reproduce

Add 802.11g devices and compare legacy and non legacy UIs

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
The addon wraps the Unifi software, you would need to log the issue upstream with Ubiquiti.
