### ISSUE TITLE
NET::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by barocio05** [hassio-addons/addon-unifi#370]
I'm a noobie in this. Yesterday it was working ok and today I tried to access to the web UI and the error showed
# Problem/Motivation

> Error of the certificate

## Expected behavior

> Load Web UI

## Actual behavior

> Privacy error because of the certificate

**Comment by frenck** [comment]
> I'm a noobie in this. Yesterday it was working ok and today I tried to access to the web UI and the error showed

This is a normal error for this application, it is because it is using a self-signed security certificate (as this is not a public service).

../Frenck
