### ISSUE TITLE
Upgrade unifi network application

### ISSUE THREAD

**Issue by lexlutor72** [hassio-addons/addon-unifi#372]
The update of the controller takes place automatically or you have to proceed with some manual procedure. My release is 7.1.66 but 7.1.68 has just been released with important updates.

**Comment by frenck** [comment]
See: #371

**Comment by lexlutor72** [comment]
I'm at the first experience .... I saw the code, but although I know Linux fairly I don't know how to use your code to upgrade. If you could give me the steps and the way I would be grateful.
Thank you.

**Comment by AlecRust** [comment]
@lexlutor72 this addon will update UniFi Network Application from 7.1.66 to 7.1.68 when the mentioned #371 PR is merged and released as a new version of this addon. You need to wait for this to happen. Updating this addon via the Home Assistant UI is the only updating you need to do.
