### ISSUE TITLE
New network aplication is v7.2.92

### ISSUE THREAD

**Issue by Wolvverine** [hassio-addons/addon-unifi#381]
The current application in HA addon has a lot of problems e.g. With firmware updates

**Comment by apospa** [comment]
How did You get new version. I need v 7.2. to migrate from current controller. Thanks

**Comment by Wolvverine** [comment]
I waiting to upgrade addon to 7.2.xx

**Comment by AlecRust** [comment]
> how can we upgrade?

You can run this software on its own to have control over the upgrade process.

Or if you want this addon to be updated, you can look at previous PRs like #375, and make a similar PR to suggest updating this addon to the latest stable version. That will make life easier for the maintainer of this plugin.

**Comment by frenck** [comment]
Closing this issue, as it is not an issue but an FR.

**Comment by Wolvverine** [comment]
@frenck @AlecRust Maybe a repository with "test" versions would be a good idea for those who want newer versions?

**Comment by frenck** [comment]
@Wolvverine Feel free to do that yourself, I have no interest in maintaining testing versions.

**Comment by Wolvverine** [comment]
"Test" this addon version not unify.

**Comment by frenck** [comment]
Same answer.
