### ISSUE TITLE
Cant Adopt Ap

### ISSUE THREAD

**Issue by kitt2011** [hassio-addons/addon-unifi#387]
Hello,

I have the following problem. I bought a used UNIFI UAC-AP. I can't get this one adopted. The Unifi add-on is installed and under settings, system, other configuration - override inform host this setting is enabled and the IP address of the home assistant is entered (192.168.178.17).

The UAC-AP was set up by the previous owner and was recognized. It said something like "the AP is assigned to another controller" under unifi devices.

I have set the UAC-AP to factory state. I also assigned it a fixed ip (192.168.178.6). It is also found under unifi devices, however I cannot adopt it. Nothing happens.
Via SSH I can connect to the UAC-AP but also here the adoption fails with the line: set-inform http://192.168.178.17:8080/inform

then comes the error message:

Adoption request sent to 'http://192.168.178.17:8080/inform'.

1. please adopt it on the controller
2. issue the set-inform command again
3. <inform_url> will be saved after device is successfully managed

Does anyone have another idea?

thanks a lot

**Comment by SirMartin** [comment]
I have kind of the same issue. I made a factory reset of a lite AP. After that I tried in multiple ways registering into the addon, and stays forever on adopting/offline infinity loop 

The UAP-AC-Lite has the latest firmware version.

I installed a Windows version of the controller and adopted without any issue. Also generated a backup in the working one, and tried to use it to restore on the addon, and I get exactly the same issue, forever in adopting status.

The only thing I found in the logs is this, but not sure is related.

`org.tuckey.web.filters.urlrewrite.UrlRewriteFilter INFO: destroy called
Exception in thread "Thread-11" java.lang.IllegalStateException: BeanFactory not initialized or already closed - call 'refresh' before accessing beans via the ApplicationContext
 at org.springframework.context.support.AbstractRefreshableApplicationContext.getBeanFactory(AbstractRefreshableApplicationContext.java:168)
 at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1172)
 at com.ubnt.service.C.Ö00000(Unknown Source)
 at com.ubnt.ace.Launcher.o00000(Unknown Source)
 at java.lang.Thread.run(Thread.java:750)`

Thanks

**Comment by perlporter** [comment]
I am also trying without success to adopt a switch and an AP.
It gets in the "adopting" loop and doesn't finish

**Comment by SirMartin** [comment]
I have just installed the windows version, and I can restore it without any issues.

![image](https://user-images.githubusercontent.com/854646/204341712-85bd7398-40e3-441b-b6d5-c9182b16c847.png)

**Comment by sinclairpaul** [comment]
Did you set the inform host?

```
Go to the settings (gears icon in the bottom left) -> System -> Application Configuration.

Toggle Override Inform Host.

Change the Host for Inform to match the IP or hostname of the device running Home Assistant.
```

**Comment by SirMartin** [comment]
> Did you set the inform host?
> 
> ```
> Go to the settings (gears icon in the bottom left) -> System -> Application Configuration.
> 
> Toggle Override Inform Host.
> 
> Change the Host for Inform to match the IP or hostname of the device running Home Assistant.
> ```

Thanks, it worked like a charm !!!
