### ISSUE TITLE
Invalid HTTPs errror in chrome

### ISSUE THREAD

**Issue by fencer** [hassio-addons/addon-unifi#388]
I am running HA on HTTPS and have had the UniFi addon for quite some time however lately in chrome I get the HTTPS error which usually I can bypass via the advanced section. However since lately there is no way to bypass the error. Can I add the HTTPS certificate to the UniFi application?
![image](https://user-images.githubusercontent.com/620966/196266566-b398cce8-e439-4187-bec5-5cc6e0e71bf2.png)

**Comment by frenck** [comment]
> Can I add the HTTPS certificate to the UniFi application?

No, that is not possible. You can use a reverse proxy as an alternative to solve this issue.

../Frenck
