### ISSUE TITLE
Version 6.0.45 for legacy UAP

### ISSUE THREAD

**Issue by krystof-k** [hassio-addons/addon-unifi#390]
I needed to get up & running UniFi Network version 6.0.45, as it is the latest version that is able to manage legacy access points.

I believe I'm not the only one who needs this and it would be really handy if it would be possible to install this version easily if there is a way to pick the version of the UniFi Network.

In the end, I managed to do it by installing an older add-on version (0.20.3), see below, which seems to be working just fine.

---

Here is what I did:

1. Download ZIP with [v0.20.3 add-on](https://github.com/hassio-addons/addon-unifi/releases/tag/v0.20.3)
2. Copy it into `/addons` and unzip (I uploaded it using VSCode add-on and then just `unzip /addons/addon-unifi-0.20.3.zip` from the Terminal & SSH addon)
3. Remove pinned versions in `unifi/Dockerfile` as they are no longer available for binutils (line 25) and openjdk-8-jdk-headless (line 30) packages:
   ```
        #binutils=2.30-21ubuntu1~18.04.5 \
        binutils \
        …
        #openjdk-8-jdk-headless=8u282-b08-0ubuntu1~18.04 \
        openjdk-8-jdk-headless \
   ```
4. Go to add-on store, open the three-dots menu (top right corner) and click _Check for updates_
5. You should see new _Local add-ons_ section
6. Install the add-on

**Comment by sinclairpaul** [comment]
Home Assistant itself doesn't support installing older versions of addons, I would suggest you log your request at the supervisor repo.  There isn't much that can be done at the addon level (it's a container with specific dependencies).

**Comment by krystof-k** [comment]
I didn't mean installing an older version of the add-on, but rather installing the older version of UniFi Network to the current add-on version. But since it is wired in the Dockerfile, I'm not sure if there is a way to set the version through some config or so.

**Comment by krystof-k** [comment]
However, I understand it may not be possible or too complicated.

[Here is the supervisor feature request](https://community.home-assistant.io/t/hass-io-api-specify-version-for-add-on-install/144340).
