### ISSUE TITLE
cannot access UI using nabucasa but ok using internal IP

### ISSUE THREAD

**Issue by parroyo-arroyo** [hassio-addons/addon-unifi#403]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
That is correct and not a bug. This is also documented in the add-on documentation.

../Frenck
