### ISSUE TITLE
Automatic Unifi Backups are not picked up in HomeAssistant backups

### ISSUE THREAD

**Issue by YashMaster** [hassio-addons/addon-unifi#406]
# Problem/Motivation

Automatic Unifi Backups are not picked up in HomeAssistant backups (at least not to my knowledge). Both Unifi and HomeAssistant backups are stored in the ./Backups directory. However, I don't believe HomeAssistant backups include anything from the ./backup directory to avoid a circular dependency... 

## Expected behavior

I would expect the UniFi backup to be stored elsewhere (or at least for us to have the ability to store it elsewhere), so it will be picked up by the HomeAssistant backup. 

## Actual behavior

Backups are stored in one of the few locations that are not backed up by HA. 

## Steps to reproduce

1. Specify an automated backup in Unifi
2. See it get logged in ./backups
3. Trigger a backup from HA
4. Unsuccessfully try to find the UniFi backup in the HA

## Proposed changes

I would love a configuration param to specify the location of the unifi backup. 
**Note**: part of the reason I care about this backup is because the full back up of Unifi Add-on is >200mb and performing daily backups of that size causes unnecessary backup storage consumption (and unnecessary disk thrashing on my poor SD card; but that's my own problem).

**Comment by frenck** [comment]
> Automatic Unifi Backups are not picked up in HomeAssistant backups

That is correct and working as intended.

> However, I don't believe HomeAssistant backups include anything from the ./backup directory to avoid a circular dependency...

Exactly, backups of backups. Which is why they are not in the same location.

> I would expect the UniFi backup to be stored elsewhere

Sorry, I don't share that.

> I would love a configuration param to specify the location of the unifi backup.

I am not going to add that; thanks for the suggestion, though.

../Frenck

**Comment by YashMaster** [comment]
@frenck - if I submitted a PR for this option, would you merge?

**Comment by frenck** [comment]
No, I have no intention of supporting such an option at this point.
