### ISSUE TITLE
Option to run older controller versions, sonoff wont connect

### ISSUE THREAD

**Issue by utzy79** [hassio-addons/addon-unifi#408]
Hi
Is there a way to run older unifi controllers.
I cannot get any of my Sonoff Devices working with this version as they have taken away the legacy devices option in the unifi controller
So I believe I need to run as older version of the controller to get these back online.
Without this, none of my lights in my house will connect to the controller properly
I have found the older versions in the Github, but no idea how to install them into Home assistant.
Thank You

**Comment by frenck** [comment]
Home Assistant doesn't have a way to provide older versions.
The only way to revert back to a previous version is by using backups (restoring those).

../Frenck
