### ISSUE TITLE
Can't install hassioaddons/unifi-amd64:0.10.0 -> 404 Client Error: Not Found

### ISSUE THREAD

**Issue by tringler** [hassio-addons/addon-unifi#41]
Hello,

I'm unable to install it on my amd64 platform due to "Can't install hassioaddons/unifi-amd64:0.10.0 -> 404 Client Error: Not Found ("no such image: hassioaddons/unifi-amd64:0.10.0: No such image: hassioaddons/unifi-amd64:0.10.0")." - Is there really no image for that platform available?

Thanks, Thomas

**Comment by frenck** [comment]
Yes, there is, the same question as your other reported issue, please provide full logs.

**Comment by tringler** [comment]
This is all what I have in the Hassio logs:
```
19-07-22 19:36:15 INFO (SyncWorker_3) [hassio.docker.interface] Pull image hassioaddons/unifi-amd64 tag 0.10.0.
19-07-22 19:36:24 ERROR (SyncWorker_3) [hassio.docker.interface] Can't install hassioaddons/unifi-amd64:0.10.0 -> 404 Client Error: Not Found ("no such image: hassioaddons/unifi-amd64:0.10.0: No such image: hassioaddons/unifi-amd64:0.10.0").
```

**Comment by tringler** [comment]
I have that problem for https://github.com/danielwelch/hassio-zigbee2mqtt, https://github.com/hassio-addons/addon-unifi/ and https://github.com/hassio-addons/addon-jupyterlab-lite, but other plug-ins are installed without any issue, so I exclude i.e. a name resolution problem.

**Comment by sinclairpaul** [comment]
As per your other issue, please validate your free disk space on your host.

**Comment by frenck** [comment]
Closing this issue. This is a double of the one of the jupyter lab add-on.
