### ISSUE TITLE
The addon stops after HA backup.

### ISSUE THREAD

**Issue by shaggee** [hassio-addons/addon-unifi#411]
# Problem/Motivation
The addon stops after HA backup.

## Expected behavior

The addon should not stop after HA done the backup or it should restart after HA done the backup.

## Actual behavior

The addon stops every time HA doing the backup. The autostart switch option is on.

## Steps to reproduce

--

## Proposed changes

Fix

**Comment by mahlzeit1948** [comment]
Not sure if it's related to HA backup, but the add on sure stops all the time, even with auto start and watchdog enabled. Looks like other users are having the same issue.
I'll be happy to donate to whoever fixes this.

**Comment by joeyhofstede** [comment]
> Not sure if it's related to HA backup, but the add on sure stops all the time, even with auto start and watchdog enabled. Looks like other users are having the same issue. I'll be happy to donate to whoever fixes this.

I've had somewhat the same problem. I migrated from a Cloudkey Gen1 to this add-on. Totally forgot that HA en Unifi backups were at the same time. Changed the Unifi backup time: Problem solved. Hope this helps.

**Comment by mahlzeit1948** [comment]
> > Not sure if it's related to HA backup, but the add on sure stops all the time, even with auto start and watchdog enabled. Looks like other users are having the same issue. I'll be happy to donate to whoever fixes this.
> 
> I've had somewhat the same problem. I migrated from a Cloudkey Gen1 to this add-on. Totally forgot that HA en Unifi backups were at the same time. Changed the Unifi backup time: Problem solved. Hope this helps

It does not. I don't have unifi backups activated.

**Comment by mahlzeit1948** [comment]
Issue still persists

**Comment by mahlzeit1948** [comment]
I ended up adding an automation that starts this addon every day. Not ideal but it is what it is
