### ISSUE TITLE
The AddOn stops unexpectedly/repeatably

### ISSUE THREAD

**Issue by michalk-k** [hassio-addons/addon-unifi#412]
# Problem/Motivation

Since the most recent version (v2.5.0) the addon occasionally stops working. It may remain working a weak, two, tree, then disappears.
I've seen a similar report just after a new version was published.
Before this version (or probably 2 back, since I skipped the previous one) the addon was rock stable and never crashed; I don't use the watchdog.

I'm open to providing any more detailed information, ie logs, if you point me to places I could gather them from.

It runs under HAOS 6.6, rPi4, 8GB

## Expected behavior

it should work indefinitely. 

## Actual behavior

see above

## Steps to reproduce

N/A

## Proposed changes

Obviously

**Comment by MartyTremblay** [comment]
I get the exact same issue. Thanks for reporting

**Comment by PrathikGopal** [comment]
I thought this was just me so I reinstalled the addon, made multiple changes but it kept crashing. Extended ram too but no go. Glad it’s reported already.

**Comment by michalk-k** [comment]
it cannot be fixed because no new version has been released since my teport

**Comment by michalk-k** [comment]
Still not fixed. v2.6.0 dies from time to time, then it's recovered by watchdog.

**Comment by PrathikGopal** [comment]
I think this is due to the google backup addon, it stops the unifi addon to make the full backup and then it fails to restore state. Watchdog appears to work sometimes but not always.

**Comment by michalk-k** [comment]
The google addon uses HA infrastructure to make a backup. in other words it calls HA command to make particular backup files. Then only think it does on top of that is copying those files to the cloud.

So, if the backup process is the root cause indeed, then there is a clash between the Unifi addon and HA supervisor (if I'm not mistaken about which component executes backups)

**Comment by 1422055** [comment]
Exact the same issu here!

**Comment by PrathikGopal** [comment]
It still occurs after every backup run, supervisor fails to start the unifi addon when the backup addon stops it.

**Comment by michalk-k** [comment]
Can confirm watchdog doesn't work with this addon (or at least not always, since very often the component remains not running)

**Comment by confuserated** [comment]
Not sure why this keeps getting marked as stale, no questions have been asked about the failure by anyone and the problem still exists, I can confirm I still get it as well.

**Comment by michalk-k** [comment]
How can it be fixed if no new version has been released in the meantime?

**Comment by michalk-k** [comment]
Still not fixed (v2.7)

**Comment by simkin** [comment]
I am experiencing the same issue on a RPi3

**Comment by SpankGirl** [comment]
I am experiencing the same issue on a NUC

**Comment by EntingChou** [comment]
I have the same problem on an Esxi

**Comment by HereticBG** [comment]
Can confirm this is still happening when the Google Backup add-on runs except I have to manually restart the add-on when I notice it died. Watchdog doesn't get it going again.

**Comment by michalk-k** [comment]
so fix to obvious bug causing application to crash is not going to be fixed?
Without the app owner comment? just by generic git message?

**Comment by krelleh** [comment]
Still same problen. 
Crash all the time. This app when from great to unusable.

**Comment by michalk-k** [comment]
Maybe I fixed the problem (not addon). 
I excluded this addon from `Home Assistant Google Drive Backup`. Hope it's not too early to celebrate. 

However, the unifi addon still deserves the fix. But obviously, the author is not interested in doing that (informing us what is happening aside)

**Comment by confuserated** [comment]
Running Add-On version 2.8.1

Home Assistant 2023.10.5
Supervisor 2023.10.1
Operating System 11.1
Frontend 20231005.0 - latest

I haven't had any reoccurrence of the problem since moving off RPi4 to Proxmox VM on Intel processor, I'm touching wood at the moment but it's more than just a coincidence I think, since I've been running for a month now with no issues.

**Comment by krelleh** [comment]
> Maybe I fixed the problem (not addon). I excluded this addon from `Home Assistant Google Drive Backup`. Hope it's not too early to celebrate.
> 
> However, the unifi addon still deserves the fix. But obviously, the author is not interested in doing that (informing us what is happening aside)

I did the same now. Hopefully it's a fix for now.

**Comment by michalk-k** [comment]
it didn't stop for amost 2 weeks now. So it's indeed the workaround

**Comment by krelleh** [comment]
> it didn't stop for almost 2 weeks now. So it's indeed the workaround

Yes. Also happy with the workaround.

**Comment by AlmightyCZ** [comment]
How did you solve backups of Unifi after excluding it from Backup schedule?

**Comment by krelleh** [comment]
Just living in the edge. Withiut backup.

**Comment by michalk-k** [comment]
> How did you solve backups of Unifi after excluding it from Backup schedule?

I think we can still backup single addon manually (from supervisor). It's needed on setting change. Partial backup on addon update is offered by HA itself. 
Yeah, it's pitta but what we can do more.
