### ISSUE TITLE
Hass Cloud: Cant access web ui to authenticate

### ISSUE THREAD

**Issue by pizzapants** [hassio-addons/addon-unifi#42]
# Problem/Motivation
After I start it, and click open wb UI, I get "the site cant be reached" 

## Steps to reproduce

Im not 100% sure this is a hass cloud issue, but I never had this issue before I switched over. 
> (How can someone else make/see it happen)

Clicking open webui will open the following URL: https://xxxx.ui.nabu.casa:8443/ which then shows the above error. 

I also get it if I access via http://hassio.local:8123

Any ideas?

**Comment by frenck** [comment]
Only add-on that support Ingress can be access via the Nabu Casa Cloud, this add-on does not support Ingress.
