### ISSUE TITLE
device_tracker not working

### ISSUE THREAD

**Issue by jujumo** [hassio-addons/addon-unifi#422]
# Problem/Motivation

device_tracker not working.

## Expected behavior

device_tracker presence on/off

## Actual behavior

device_tracker always responding "unavailable"

## Steps to reproduce

update  UniFi Network Application to version: 2.6.0 
I tried to "configure" the integration, but it has not effect.

**Comment by frenck** [comment]
`device_tracker` that sounds like an issue with an Home Assistant integration.

This is not an Home Assistant integration, I think you are mixing things up.

../Frenck

**Comment by jujumo** [comment]
OK, sorry, Its just it happened with last add-on update (2.6.0), and disappeared when I rolled back (2.5.0), so I assumed it was add-on fault.
