### ISSUE TITLE
inform host is set to container ip

### ISSUE THREAD

**Issue by BWhitten** [hassio-addons/addon-unifi#428]
If you try and adopt an AC-Pro on the network, the AP receives the inform host with the unifi container IP and not the homeassisant IP.
Adoption then fails.

To workaround you must go into the unifi advanced configuration and set the inform host override.

**Comment by sinclairpaul** [comment]
This is stated in the documentation - <https://github.com/hassio-addons/addon-unifi/blob/main/unifi/DOCS.md#installation>
