### ISSUE TITLE
Add on doesn't start

### ISSUE THREAD

**Issue by djtommye** [hassio-addons/addon-unifi#43]
# Problem/Motivation

Does not start

## Expected behavior

It should start

## Actual behavior

Doesn't start

## Steps to reproduce

Install.  Click start.  

## Proposed changes

Fix it. ;-)

Running on Rasbpi 3.  Hassio 0.96.5 - I get this error:

19-07-28 00:32:40 ERROR (SyncWorker_12) [hassio.docker] Can't start addon_a0d7b954_unifi: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint addon_a0d7b954_unifi (0193b68130ac82c46619cda06fe0fd5da5de8eb1613f5276b156e07916dc4acf): Error starting userland proxy: listen tcp 0.0.0.0:8080: bind: address already in use")

**Comment by frenck** [comment]
The issue in is in the message: `Error starting userland proxy: listen tcp 0.0.0.0:8080: bind: address already in use`

Port `8080` is already in use. Two options:
- Change the port of the add-on
- Change the port of the other thing/add-on that uses that port.
