### ISSUE TITLE
Devices status are not updated

### ISSUE THREAD

**Issue by Wassini** [hassio-addons/addon-unifi#439]
# Problem/Motivation

> Devices status are not updated. Online clients are shown offline.

## Expected behavior

> The status for a devices must reflect the actual status of the device. 

## Actual behavior

> An AP is shown as "Isolated", but is actual working.
> Clients are shown offline, but have full access to the network.

## Steps to reproduce

> I wouldn't know. Maybe the log can tell you something
> My setup is using several APs in a mesh network
> Internet -> USG -> US-8-60W -> U6-LR
>    ... (mesh) UAP-AC-Pro -> US-8-60W -> PCs
>    ... (mesh) UAP-AC-Pro -> US-8-60W 

## Log

> See attachment

![log 2023-07-27 224439](https://github.com/hassio-addons/addon-unifi/assets/17749701/1053b334-3d3f-4d84-820e-e8dfc041181f)

**Comment by rivasabb** [comment]
Same here, same backup restored into another docker on a separate machine works so its local to HAOS install.
