### ISSUE TITLE
404 Error on all pages

### ISSUE THREAD

**Issue by nhorvath** [hassio-addons/addon-unifi#441]
# Problem/Motivation

All the urls including the root url give 404 errors.

## Expected behavior

It to work as it used to

## Actual behavior

404 Errors

Logs:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: UniFi Network Application
 Manage your UniFi network using a web browser
-----------------------------------------------------------
 Add-on version: 2.7.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (amd64 / qemux86-64)
 Home Assistant Core: 2023.7.0
 Home Assistant Supervisor: 2023.08.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[14:06:31] INFO: Configuring timezone (America/New_York)...
s6-rc: info: service base-addon-timezone successfully started
Log level is set to INFO
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-unifi: starting
s6-rc: info: service init-unifi successfully started
s6-rc: info: service unifi: starting
s6-rc: info: service unifi successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[14:06:32] INFO: Now starting the UniFi Network Application...
[14:06:32] INFO: Note: No add-on specific logs beyond this point.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.catalina.loader.WebappClassLoaderBase (file:/usr/lib/unifi/lib/tomcat-embed-core-9.0.65.jar) to field java.io.ObjectStreamClass$Caches.localDescs
WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "launcher" java.lang.NullPointerException: Web context failed to initialize
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at com.ubnt.net.OoOO.ØÒ0000(Unknown Source)
	at com.ubnt.net.OoOO.Òo0000(Unknown Source)
	at com.ubnt.service.D.StringObject(Unknown Source)
	at com.ubnt.ace.Launcher.class(Unknown Source)
	at com.ubnt.ace.Launcher.main(Unknown Source)
```

## Steps to reproduce

Unknown, but this used to work for me and now it doesn't.

## Proposed changes

???

**Comment by nhorvath** [comment]
Any idea why I can't seem to restore my 2.6.0 partial backup? It doesn't seem to do anything or log any error when I try.

**Comment by ksya** [comment]
I have the same problem now after upgrade to HA 2023.9.1

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: UniFi Network Application
 Manage your UniFi network using a web browser
-----------------------------------------------------------
 Add-on version: 2.7.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.5  (amd64 / qemux86-64)
 Home Assistant Core: 2023.9.1
 Home Assistant Supervisor: 2023.08.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[13:40:49] INFO: Configuring timezone (Europe/Amsterdam)...
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-unifi: starting
s6-rc: info: service init-unifi successfully started
s6-rc: info: service unifi: starting
s6-rc: info: service unifi successfully started
s6-rc: info: service legacy-services: starting
[13:40:50] INFO: Now starting the UniFi Network Application...
[13:40:50] INFO: Note: No add-on specific logs beyond this point.
s6-rc: info: service legacy-services successfully started
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.catalina.loader.WebappClassLoaderBase (file:/usr/lib/unifi/lib/tomcat-embed-core-9.0.65.jar) to field java.io.ObjectStreamClass$Caches.localDescs
WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[13:41:30] INFO: Service UniFi Network Application exited with code 256 (by signal 9)
[13:41:31] INFO: Now starting the UniFi Network Application...
[13:41:31] INFO: Note: No add-on specific logs beyond this point.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.catalina.loader.WebappClassLoaderBase (file:/usr/lib/unifi/lib/tomcat-embed-core-9.0.65.jar) to field java.io.ObjectStreamClass$Caches.localDescs
WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[13:42:10] INFO: Service UniFi Network Application exited with code 256 (by signal 9)
[13:42:10] INFO: Now starting the UniFi Network Application...
[13:42:10] INFO: Note: No add-on specific logs beyond this point.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.catalina.loader.WebappClassLoaderBase (file:/usr/lib/unifi/lib/tomcat-embed-core-9.0.65.jar) to field java.io.ObjectStreamClass$Caches.localDescs
WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release`

**Comment by nhorvath** [comment]
I had to remove and reinstall the addon and restore unifi from a config
backup

**Comment by rmeekers** [comment]
This seems to be the same issue as #446
