### ISSUE TITLE
New AP stuck in Adopting status

### ISSUE THREAD

**Issue by mathieudebieuvre** [hassio-addons/addon-unifi#442]
# Problem/Motivation

> When adding a new AP to the UniFi Network Manager, the AP is stuck in "Adopting" status and never actually gets adopted with the configuration pushed.

## Expected behavior

> The AP should be adopted and the wifi configuration pushed to it.

## Actual behavior

> AP stuck in Adopting state

## Steps to reproduce

> Factory reset an AP, it will show-up in the UnFi Network Manager as unpaired, then try to Adopt it.

## Configuration

> Running the latest version of hassio (10.4) / ha (2023.8.1) / addon-unifi (2.7). The only other installed add-on is "Terminal & SSH" which is unlikely to cause a conflict.

Note: The AP was successfully paired to a UniFi Network Manager running on a Mac OS install. So the AP clearly works.
Trying to migrate it with a backup/restore from Mac OS to HA was unsuccessful, with the AP back in Adopting status and stuck there again.

**Comment by sinclairpaul** [comment]
Did you follow the documentation to set the Inform Host?

**Comment by mathieudebieuvre** [comment]
Completely missed that part, thanks so much for pointing it out ! This solved the problem.
