### ISSUE TITLE
access points need re-adopting after every update to Hass.io

### ISSUE THREAD

**Issue by nathanscrivener** [hassio-addons/addon-unifi#45]
# Problem/Motivation

> after every update to Hass.io, or restoring from a snapshot, the Unifi Access Points are no longer adopted. This necessitates using ssh to send a set-inform command in each access point.

## Expected behavior

> for the access points to remain in an adopted state through updates.

## Proposed changes

> I'm not sure, as I lack the skills to do anything to help, however I am reporting this with the hope that someone else might be able to figure it out.

**Comment by frenck** [comment]
Follow the installation steps of the manual, you have to correct the inform host in the controller settings as well.
