### ISSUE TITLE
Migrating from 7.5.174 to this addon?

### ISSUE THREAD

**Issue by tjkcc** [hassio-addons/addon-unifi#452]
I am running controller 7.5.174 in docker on my NAS and want to move to this addon, but it's running 7.4.162. Any ideas on how to do it or my best option is just to wait for the versions to match? The issue is the settings file I have is only from v7.5.174 and setting up from scratch doesn't sound like fun.

**Comment by tjkcc** [comment]
Looks like v 7.5.176 is out too. Guess I'll need to wait for an update to that one

**Comment by frenck** [comment]
Correct! 👍 

Feel free to open up a PR.

../Frenck
