### ISSUE TITLE
Move to 7.5.176

### ISSUE THREAD

**Issue by bridavis** [hassio-addons/addon-unifi#453]
# Problem/Motivation

Looking to move the add-on to latest official build (7.5.176).

## Expected behavior

When upgrading the add-on, controller version 7.5.176 is provided.

## Actual behavior

Add-on currently uses 7.4.162.

## Steps to reproduce

Install current version of add-on.

## Proposed changes

Update Dockerfile to include 7.5.176 binary.

**Comment by frenck** [comment]
Feel free to open up a PR 👍 

../Frenck

**Comment by bridavis** [comment]
Yup, plan to do this - was following the contribution instructions to communicate before pulling PR.
This, however, leads to a bigger question which is if this is not planned, is this support for this add-on ending?

**Comment by frenck** [comment]
> if this is not planned

Planned? This is not a company.

> is this support for this add-on ending?

Hope not, I use it myself...

**Comment by bridavis** [comment]
<img width="469" alt="image" src="https://github.com/hassio-addons/addon-unifi/assets/2539447/cd7b2ba2-efa0-4555-901a-9780e90956e5">

**Comment by frenck** [comment]
Sure, it is not an issue but a request. I will close that.
