### ISSUE TITLE
Update to Unifi Controller version 7.5.176

### ISSUE THREAD

**Issue by plebcity** [hassio-addons/addon-unifi#454]
# Problem/Motivation

New version has lots of new features and uses Java 17
https://community.ui.com/releases/UniFi-Network-Application-7-5-176/0a224764-0603-4a8b-a038-1a7d59c6615c

## Proposed changes

Upgrade to 7.5.176 keeping in mind the other upgrades that are needed aswell (Java 17, Mongo 3.6+)

**Comment by frenck** [comment]
Closing as this is not an issue but an feature request.

Feel free to contribute.

../Frenck
