### ISSUE TITLE
Would be great to have explanation, audience, whois it for

### ISSUE THREAD

**Issue by romanr** [hassio-addons/addon-unifi#459]
# Problem/Motivation

I have the managed Unifi network with UDM. And I have Home Assistant.
I stumbled on this package and at first I thought it's for running Ubiquiti's web interface within HA. But screenshots are different.
Maybe it's for those who has no UDM /UDM-Pro or any management portal?
Looking at Github page, no explanation either.  

## Expected behavior

Indication who is the audience or why this is needed, that would be great!

**Comment by sinclairpaul** [comment]
The about section in the documentation pretty much covers it, especially:

 ```This add-on runs Ubiquiti Networks' UniFi Network Application software```

If you have a UDM, you don't need it, as you run the controller there.

**Comment by romanr** [comment]
> This add-on runs Ubiquiti Networks' UniFi Network Application software

Yes I have read the above sentence few times. And was thinking  - why especially on screenshots it looks different, is it with better support for HA.?   
It should state "for those who don't have UDM"
