### ISSUE TITLE
unifi controller fails to start on new hassio install

### ISSUE THREAD

**Issue by iannecj** [hassio-addons/addon-unifi#46]
# Problem/Motivation
unifi controller fails to start

## Expected behavior

controller starts

## Actual behavior

goes green after clicking startt but on refresh off line, never started.

Here are the log entries from a restart attempt:
19-08-09 10:47:16 INFO (SyncWorker_6) [hassio.docker.interface] Clean addon_a0d7b954_unifi application
19-08-09 10:47:18 INFO (SyncWorker_6) [hassio.docker.addon] Start Docker add-on hassioaddons/unifi-armv7 with version v0.10.0
19-08-09 10:47:19 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_unifi

## Steps to reproduce

fresh install and click start.  I am on a raspberry pi 4b

## Proposed changes

Guessing this is my user ignorance but though Id check.

**Comment by frenck** [comment]
Please provide add-ons logs

**Comment by iannecj** [comment]
Thank you so much for this help as I know now this is user error on my part.   I am so green I didn't see this additional log before I wrote and I see my issue is ssl related.  If I set ssl to false it starts but when I get in there it doesnt recongize my unifi devices.  Does ssl need to active for it to work?
Hass.io Add-on: UniFi Controller
 Manage your UniFi network using a web browser
-----------------------------------------------------------
 Add-on version: 0.10.0
 You are running the latest version of this add-on.
 System: HassOS 3.3  (armv7 / raspberrypi4)
 Home Assistant version: 0.97.0
 Supervisor version: 170
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] unifi.sh: executing... 
[08:20:46] FATAL: 
[08:20:46] FATAL: SSL has been enabled using the 'ssl' option,
[08:20:46] FATAL: this requires a SSL certificate file which is
[08:20:46] FATAL: configured using the 'certfile' option in the
[08:20:46] FATAL: add-on configuration.
[08:20:46] FATAL: 
[08:20:46] FATAL: Unfortunately, the file specified in the
[08:20:46] FATAL: 'certfile' option does not exists.
[08:20:46] FATAL: 
[08:20:46] FATAL: Please ensure the certificate file exists and
[08:20:46] FATAL: is placed in the Hass.io '/ssl/' directory.
[08:20:46] FATAL: 
[08:20:46] FATAL: In case you don't have SSL yet, consider getting
[08:20:46] FATAL: a SSL certificate or setting the 'ssl' option
[08:20:46] FATAL: to 'false' in case you are not planning on using
[08:20:46] FATAL: SSL with this add-on.
[08:20:46] FATAL: 
[08:20:46] FATAL: Check the add-on manual for more information.
[08:20:46] FATAL: 
[cont-init.d] unifi.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by frenck** [comment]
> Be sure to check the log above, line by line, for hints.
