### ISSUE TITLE
Wifi stops working when updating to HAOS 11.0 or 11.1

### ISSUE THREAD

**Issue by brent0np** [hassio-addons/addon-unifi#461]
# Problem/Motivation

Wifi stops working when updating HAOS to 11 or 11.1

## Expected behavior

Wifi to continue to operate as normal

## Actual behavior

Wifi network no longer available. Access points require readopting which fails.

Log:

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------

 Add-on: UniFi Network Application
 Manage your UniFi network using a web browser
-----------------------------------------------------------
 Add-on version: 2.8.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.1  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.10.5
 Home Assistant Supervisor: 2023.10.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[16:01:32] INFO: Configuring timezone (Australia/Brisbane)...
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-unifi: starting
s6-rc: info: service init-unifi successfully started
s6-rc: info: service unifi: starting
s6-rc: info: service unifi successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[16:01:35] INFO: Now starting the UniFi Network Application...
[16:01:35] INFO: Note: No add-on specific logs beyond this point.
:118 TCP candidates not supported yet
:118 TCP candidates not supported yet
:118 TCP candidates not supported yet
:1023 Permanent error code on channel bind request: 403 - Forbidden IP
:484 All TURN channel bindings failed`

## Steps to reproduce

Upgrade HAOS to 11 or 11.1 on RPI4
Wireless stops working and shows access points require adoption. Adoption fails.  I have tried removing and re-adding the inform address but this made no difference. I then downgraded to HAOS 10.5 and wifi operated as normal

## Proposed changes

None

**Comment by Dude4Linux** [comment]
I believe I'm experiencing this problem since upgrading to version 11.x.  Running HAOS on a Raspberry Pi 4 the built-in WiFi periodically gets disabled and has to be restored.
Core            2023.11.3
Supervisor   2023.11.3
Operating System  11.1
Frontend      20231030.2

I'm not sure why I'm seeing this as an issue with addon-unifi. Although I have the addon installed, I don't think its related to the WiFi problem.

**Comment by brent0np** [comment]
It turns out my issue was DHCP.  The adoption wouldn't progress as upgrading to HAOS 11 required a change to DHCP configuration (i had to change to end0).  Once I diagnosed enough to rosolve the DHCP issue the adoption progressed.

**Comment by brent0np** [comment]
closed

**Comment by AlecRust** [comment]
@brent0np could you detail the DHCP change you made, and where you made it? Thanks
