### ISSUE TITLE
Add-on 3.0.0 not starting and crashing HA

### ISSUE THREAD

**Issue by sebastianlorenzen** [hassio-addons/addon-unifi#462]
Fresh HA installation on a Raspberry Pi - updated to the latest version.
Wehen I try to start the addon, it does nothing. From time to time ha is crashing and restarting.

In the Log not much:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: UniFi Network Application
 Manage your UniFi network using a web browser
-----------------------------------------------------------
 Add-on version: 2.8.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.1  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.11.2
 Home Assistant Supervisor: 2023.11.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[23:20:17] INFO: Configuring timezone (Europe/Berlin)...
Log level is set to DEBUG
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-unifi: starting
s6-rc: info: service init-unifi successfully started
s6-rc: info: service unifi: starting
s6-rc: info: service unifi successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[23:20:21] INFO: Now starting the UniFi Network Application...
[23:20:21] INFO: Note: No add-on specific logs beyond this point.

at this point ha is crashing.

I have removed and reinstalled the addon, no change.

Any ideas how to troubleshoot this. I'm also a bit new to HA, so I migh not see all logs etc.
After the crash all other logs are empty, so I could not see what is going on.

Thanks, Sebastian

**Comment by sebastianlorenzen** [comment]
Hello Team, I just updated to 3.0.0, still same problem. I have reinstalled HA from scratch only Unify Addon installed, same issue. Every time I start the addon, HA is crashing and all logs are gone. Any idea how to keep the logs from before the crash?

**Comment by frenck** [comment]
Sounds like you are running out of memory and the OOM killer tries to save the system.

**Comment by sebastianlorenzen** [comment]
Hm, it is a 4GB Pi. Let me check this.

**Comment by sebastianlorenzen** [comment]
@frenck, good catch. would be nice to see something in the logs or a warning.
I increased the swap file to 2048mb and I was able to start the container.

**Comment by frenck** [comment]
> would be nice to see something in the logs or a warning.

We can't. That is the point / problem when the OOM killer comes by.

Anyways, glad you found a solution for your issue 👍 

../Frenck
