### ISSUE TITLE
Prompts for version upgrade but needs addon change to new 8.0.7 version

### ISSUE THREAD

**Issue by Zorkny** [hassio-addons/addon-unifi#465]
# Problem/Motivation

Need update to latest version
## Expected behavior

Was not able to create a PR and test it, but this is the new URL to the latest version to use in the Docker-file
https://dl.ui.com/unifi/8.0.7/unifi_sysvinit_all.deb

## Actual behavior

New version to be downloaded

## Steps to reproduce

Controller alerts on new version but it cant be upgraded in the addon

## Proposed changes

Update the addon in the Docker file with the new URL to the new version - https://dl.ui.com/unifi/8.0.7/unifi_sysvinit_all.deb
If you have an instruction how I can test my PR in my own haos Im happy to create a PR.

**Comment by Zorkny** [comment]
@frenck if you have any instruction how I can test my own PR on haos I can do one, but I really think its only the URL that needs to change to - https://dl.ui.com/unifi/8.0.7/unifi_sysvinit_all.deb in the Dockerfile.

**Comment by sinclairpaul** [comment]
The documentation can be found at https://developers.home-assistant.io/docs/add-ons

Please don't open issues for version bumps if it doesn't fix an existing issue, it will be done when it's done.
