### ISSUE TITLE
Trying to import backup from old controller to move to new controllor on HA

### ISSUE THREAD

**Issue by skank01** [hassio-addons/addon-unifi#471]
Hi
Trying to import a backup, i get warning "Cannot use backup file from newer version"

Old controller is version 8.0.24
In home assitant addon, controller seems to be Addon version 3.0.0 version network application 8.0.7

How can i restore from my old backup?

**Comment by cfergeau** [comment]
Your best option is to wait for the Addon to be updated to 8.0.24, there's already a PR for that https://github.com/hassio-addons/addon-unifi/pull/469

**Comment by skank01** [comment]
> Your best option is to wait for the Addon to be updated to 8.0.24, there's already a PR for that #469

Perfect, hopefully soon :)

**Comment by MikeBookham** [comment]
I can confirm that a backup from another Unifi controller running v8.0.24 on a WIndows 11 Home PC can be successfully imported into HAOS 2023.12.14 with this updated version (v3.0.1) of this addon.

**Comment by sinclairpaul** [comment]
<https://github.com/hassio-addons/addon-unifi/releases/tag/v3.0.1>

Addon is now running 8.0.24
