### ISSUE TITLE
Unifi Home Assistant

### ISSUE THREAD

**Issue by NewSmokie** [hassio-addons/addon-unifi#473]
Hello everyone, I'm new here. I'm currently setting up my home assistant and have the problem that I can't get my Unifi integrated into the home assistant.
I watched every video and read the descriptions, unfortunately to no avail.
I got so far that I installed the addon and then started it. I'm not getting any further

thank you for your help

**Comment by frenck** [comment]
This is the issue tracker of the add-on? Not the Home Assistant integration.

If you need support on using home Assistant, I recommend going to the Home Assistant community forums or Discord chat.

Thanks!

../Frenck
