### ISSUE TITLE
Feature Request: config.gateway.json (again, now with 'addon_configs' mount)

### ISSUE THREAD

**Issue by Aephir** [hassio-addons/addon-unifi#475]
I hope I'm not completely off here, but doesn't the new `addon_configs` mount present a way to circumvent the issues raised with being able to use `config.gateway.json`?

#12 , #35 , #38 , #122 , #271 

(and if I am, sorry for kicking a dead horse)

**Comment by frenck** [comment]
Yeah now that is available, that might be a good one to add at this point 👍 

../Frenck

**Comment by myhades** [comment]
Is there any update on this one?

**Comment by frenck** [comment]
Nope, feel free to contribute it though 👍

**Comment by Aephir** [comment]
I still think this would be useful to a lot of people, so I'll keep it alive, hoping someone had the skill and will to look into this.
