### ISSUE TITLE
Access to SSH?

### ISSUE THREAD

**Issue by Scoperius** [hassio-addons/addon-unifi#485]
I have a problem with changing Wan IP address in my Unifi controller. I was just instructed by Unifi support to do the following:

***********************
"You need to install the mongodb file on the system running the UniFi Network application. On that system, you need to run those commands.

Copy the complete output result and share it here on this ticket. 
 
mongo --port 27117 ace
db.networkconf.find().pretty()

It will give detailed information about where those IPs are being used, and with the help of SSH commands, we can remove them. That should fix the issue. "
***************************

But I did not find the way how to do that. Can you please help?  

Thanks, Petr

**Comment by frenck** [comment]
You can't in this eco system.

Best approach/solution is to restore a backup to the point it did work.

../Frenck

**Comment by Scoperius** [comment]
Hi Frenck,

why it is not possible to simple access SSH on any port? It could be 
very simple for you as a developer and to add and this functionality can 
help to proceed with everything what is needed.

Petr




------ Původní zpráva ------
Od "Franck Nijhof" ***@***.***>
Komu "hassio-addons/addon-unifi" ***@***.***>
Kopie "Scoperius" ***@***.***>; "Author" 
***@***.***>
Datum 02.02.2024 14:50:35
Předmět Re: [hassio-addons/addon-unifi] Access to SSH? (Issue #485)

**Comment by frenck** [comment]
> why it is not possible to simple access SSH on any port? 

It isn't needed and this isn't an SSH add-on.

../Frenck
