### ISSUE TITLE
unable to use "Restore Server from a Backup" from clean install

### ISSUE THREAD

**Issue by chenks** [hassio-addons/addon-unifi#486]
on a clean/fresh install of the unifi network application add-on i wish to restore from a backup, however when clicking on "Restore Server from a Backup" on the initial setup splash screen it loads a blank white page with no options to do anything.

it seems to try to load https://<ipaddress>:8443/setup/restore/backups, but the page is completely white.

add-on version : 3.0.3
Core : 2024.1.6
Operation System 11.4
Frontend 20240104.0

tested on both Chrome and Edge.

**Comment by renewoensdregt** [comment]
Workaround is to install from scratch and then upload in settings. Not sure why this is happening
________________________________
From: chenks ***@***.***>
Sent: Monday, February 5, 2024 11:35 AM
To: hassio-addons/addon-unifi ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hassio-addons/addon-unifi] unable to use "Restore Server from a Backup" from clean install (Issue #486)


on a clean/fresh install of the unifi network application add-on i wish to restore from a backup, however when clicking on "Restore Server from a Backup" on the initial setup splash screen it loads a blank white page with no options to do anything.

it seems to try to load https://:8443/setup/restore/backups, but the page is completely white.

add-on version : 3.0.3
Core : 2024.1.6
Operation System 11.4
Frontend 20240104.0

tested on both Chrome and Edge.

**Comment by cfergeau** [comment]
For what it's worth, I do not see this issue on a mac with firefox/safari and version 3.0.3 of the addon.
