### ISSUE TITLE
Update logo and icon of UniFi

### ISSUE THREAD

**Issue by kongo09** [hassio-addons/addon-unifi#489]
# Problem/Motivation

> The icon and logo of Unifi are outdate

## Expected behavior

> Show current icon and logo

## Actual behavior

> Show outdated icon and logo

## Steps to reproduce

> Visit add-on info page

## Proposed changes

> Update icon and logo

![icon@2x](https://github.com/hassio-addons/addon-unifi/assets/640121/1fead590-c864-4f29-91c2-0783f537426b)

![dark_logo@2x](https://github.com/hassio-addons/addon-unifi/assets/640121/591b9293-6c99-4d0e-84fd-8ce941ff89aa)

![logo@2x](https://github.com/hassio-addons/addon-unifi/assets/640121/8be2dba1-f220-47b9-815e-f5a3f9b5b523)

**Comment by sinclairpaul** [comment]
Feel free to raise a Pull Request, this isn't an issue with functionality.

**Comment by renewoensdregt** [comment]
I just did this. New pull request created.
