### ISSUE TITLE
ADOPTION ISSUES

### ISSUE THREAD

**Issue by vpedro2022** [hassio-addons/addon-unifi#492]
# Problem/Motivation

> i cant adopt my AP (U6 LR, U6 LITE),devices, is not working. 

## Expected behavior

> normal ap adoption

## Actual behavior

> no adoption

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by keionbis** [comment]
I am also having this issue. I just started on it so i havent been able to dive any further into it yet

**Comment by badamik** [comment]
I have the same issue. I have AP U6 LR. It is visible for adoption, but after few seconds of 'adopting phase' it (AP) becomes offline. After few seconds tries again to adopt

**Comment by FlipperMike67** [comment]
Hi, don't forget to change the settings in the Unifi controller, see picture below.
This solved my issue.

![UnifiController_Homeassistant](https://github.com/hassio-addons/addon-unifi/assets/162920247/5c874d8a-a805-4991-89a4-78d323ea733b)

**Comment by badamik** [comment]
@FlipperMike67 - thanks this solved my issue ! 

![image](https://github.com/hassio-addons/addon-unifi/assets/6852171/0e626c6d-33cb-446c-973f-9aa93afb4854)

**Comment by keionbis** [comment]
Me too! Thanks!

**Comment by vpedro2022** [comment]
Hi guys, on my case i was only able to adopt using instead of the name "homeassistant" i use the up address. Now is working. Many thanks to all.
