### ISSUE TITLE
Cannot find Unifi AP to connect 

### ISSUE THREAD

**Issue by rlust** [hassio-addons/addon-unifi#5]
# Problem/Motivation
Cannot find AP
> (Why the issue was filed)
Doe not function
## Expected behavior
Finds current APLR
> (What you expected to happen)
Find available AP
## Actual behavior
Get the following:
UniFi Access Point Required
Please connect at least one  to enable the channel charts.
> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)
Running HASSIO .773 UNIFI add on 0.2.1
## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Hi there,

Thank you for opening an issue, however, I run this add-on myself on my production system as well, with multiple AP's connected.

Are you sure you have followed the installation steps accurately?

https://github.com/hassio-addons/addon-unifi#installation

It sounds like you've skipped step 6 to 10.

**Comment by rlust** [comment]
Thanks for the reply.
I have followed the steps,
for _Controller Hostname/IP_ I entered 192.168.1.176 my HASSIO ip address. 
Is this correct? after step 10 should it find the AP?
