### ISSUE TITLE
Restore from backup fails

### ISSUE THREAD

**Issue by rcmaehl** [hassio-addons/addon-unifi#500]
# Problem/Motivation

> Attempting to migrate from an old controller to the HA controller fails.

## Expected behavior

> Site export file restores and able to sign in

## Actual behavior

> Invalid username and/or password error

## Steps to reproduce

> Sign into existing controller
> Go to settings -> Export Site
> Install addon-unifi
> Restore from backup
> Attempt to sign in

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by rcmaehl** [comment]
Choosing "Forgot Password" fails with `This email address is not registered to receive password reset requests from your UniFi Network Server. `

**Comment by rcmaehl** [comment]
Commenting so this doesn't get closed. Considering no new releases for addon-unifi have occurred, it should still occur

**Comment by sinclairpaul** [comment]
It likely fails due to the history import, try restoring only config.

**Comment by dankfred** [comment]
I'm having the exact same issue, tried restoring a backup with and without history, same result.

**Comment by rcmaehl** [comment]
I was eventually able to work around this by setting up the HA Unifi Add-on and then restoring from backup within the settings but I had to manually re-adopt all my APs over SSH plus some additional workarounds for auto-adopt failing from the unifi forums.

**Comment by dankfred** [comment]
Yeah I tried doing that with no luck. However, I did install the pc version, restored the backup there, inspected the database just to see that because my backup was from a UDR, the backup did not include a password, since the password is handled by the console backup instead. Manually editing the password and then backing up again, to restore on this addon did the trick!
