### ISSUE TITLE
Add-on seems to cause HA crash

### ISSUE THREAD

**Issue by Vinisz** [hassio-addons/addon-unifi#503]
# Problem/Motivation

With the plugin enabled, HA crashes every night at 2:00 AM exactly, with add-on disabled, HA stays stable, is there something like a maintanance routine in Unifi which can cause this ? 

## Expected behavior

Normal running add-on without HA crashes

## Actual behavior

HA crashing every night at 2:00 AM with add-on enabled

## Steps to reproduce

Enable add-on, HA will crash every night

## Proposed changes

Provide workaround to keep add-on running (maybe change some unifi config? ) or permanent fix

**Comment by cfergeau** [comment]
Maybe backups are triggered at that time? Does your hardware have enough memory for your HA + Unifi workload?

**Comment by Vinisz** [comment]
I run HA on an intel NUC I5 with 32Gb memory so yeah, I think that should be more then enough.. 
Backups are disabled in Unifi, so that can not be the case, I do see I have "automatisch device upgrades " enabled around that time, seems strange that that causes any issues but I disabled it now, let's see.

**Comment by Vinisz** [comment]
Add-on still crashes HA, even with "automatic device upgrades" disabled but I noticed it's not at 2:00 AM anymore but at a random time. I'll investigate some more and will post results here.

**Comment by renewoensdregt** [comment]
As mentioned before I suspect some kind of memory issue. Even if your NUC has enough memory, maybe the container doesn’t get or use all. Is strart tracking memory usage and see
________________________________

**Comment by Vinisz** [comment]
How can i track the memory usage or spot the memory leak ?
Will there be an error/warning reported ?
I already adjusted the "logging level" for the add-on but I don't see much of a difference.

There are however other errors reported like this:

`:0 Permanent error code on channel bind request: 400 - Empty port number in channel bind request
:0 All TURN channel bindings failed
:0 Unable to read data from SCTP socket. Permanent error: (104) Connection reset by peer
:0 SCTP ingest failed
:0 SCTP ingest failed
:0 Unable to do SSL I/O
:0 webRtcId 1 terminated with code: (-2147090409) WebRTC connection interrupted from far side
:0 Permanent error code on channel bind request: 400 - Empty port number in channel bind request
:0 All TURN channel bindings failed`

But I'm unsure if that is really the problem (it's not like the crash is happening directly after that error)

**Comment by Vinisz** [comment]
In the meantime, I assigned more memory to the add-on, however, after running for two days, it again crashed at exactly 02:00 AM.
Logs still not saying much about a memory issue or something like that, still no idea what's going on

![image](https://github.com/hassio-addons/addon-unifi/assets/49644964/ced5e7c2-dca3-433b-95ef-ed66069d027c)

**Comment by Vinisz** [comment]
Any updates here ?

**Comment by stryk3rr3al** [comment]
I came here hoping someone had posted some kind of fix. I'm contemplating moving my Unifi controller off Home assistant.

**Comment by Vinisz** [comment]
latest update also does not help, still no information in the logging

**Comment by Vinisz** [comment]
Tried even more memory, does not help.. Also nothing clear in the logs on what the issue really is (memory was just a "guess" from dev) , I think I'm giving up on this and moving the Unifi controller away from HA (maybe onto dedicated RpI or something)
