### ISSUE TITLE
cant adopt wifi access point. Server reject state

### ISSUE THREAD

**Issue by vpaulos** [hassio-addons/addon-unifi#506]
into AP in ssh session we put set-inform http://192.168.220.10:8080/inform command
addon was started and I can logon into web interface via http://192.168.220.10:8443/ page
192.168.220.10 - it is local ip address of hassos instalation.
in advanced system setting I changed inform host for my ip address
all was restarted and AP was reseted to default.

it still in rejected mode and in web site I cant see my AP. 
I need any help!
p.s. while direct curl for inform page at http://192.168.220.10:8080/inform - I see rejected or no working page on google chrome.

**Comment by jonaskor** [comment]
I think this post should help: https://community.home-assistant.io/t/unifi-ap-inside-unifi-controller-stays-in-adopting/152724
