### ISSUE TITLE
Unifi addon use a lot of space

### ISSUE THREAD

**Issue by diybateriaslifepo4** [hassio-addons/addon-unifi#508]
Hello, I am realizing that my home assistant backups take up a lot of space, investigating further I see that the unifi addon is weighing 1.5Gb in the backup, I have investigated but I can't find a reason for it to take up so much, since the backup copies within unifi only occupy about 70Mb.

## Expected behavior

What I hope is that the unifi backup used something coherent

## Steps to reproduce

Do a home assistant backup of unifi addon

## Proposed changes

Is it normal for some reason?
Is it just my mistake? how can I solve that?
Is it a bug in the addon? can you solve it?

Thanks!
![Unifi backups](https://github.com/hassio-addons/addon-unifi/assets/80992172/84ff2b1a-6ad4-4979-b448-b0753529646d)
![HA backup](https://github.com/hassio-addons/addon-unifi/assets/80992172/297d034c-365b-4e1c-b68d-4decfdacb487)

**Comment by frenck** [comment]
This is not a bug with the add-on, but how UniFi works. They use MongoDB under the hood, which allocates space ahead of time.

../Frenck

**Comment by diybateriaslifepo4** [comment]
Ok, I understand, but couldn't something be done to be able to keep the unifi backup within the ha bakcup without having to copy the entire addon?

I have seen that the internal unifi backup is saved in /backup/unifi/autobackup, but this folder is not accessible by the HA backup component, perhaps it could be configured to move or duplicate it to another folder that I can select in a copy of HA?

for example in the shared folder

Thanks for the reply and your work.
![image](https://github.com/hassio-addons/addon-unifi/assets/80992172/07c8f1be-7dc3-4a91-84cf-b8c33ff6f9fd)

**Comment by frenck** [comment]
> without having to copy the entire addon?

That makes no sense to me. The add-on backup feature... is to backup the add-on...

If you rather use the backup functionality of UniFi itself, be my guest and use that instead 🤷
