### ISSUE TITLE
Feature request: Add ability to restart switch devices / check uplink "Experience" connection state

### ISSUE THREAD

**Issue by Grandma-Betty** [hassio-addons/addon-unifi#510]
On the UniFi UI it is possible to restart switch devices with the additional ability to power cycle PoE port if available:
![Screenshot 2024-06-06 125423](https://github.com/hassio-addons/addon-unifi/assets/48346793/53c60d3c-fa0b-4a87-9903-6c6a319509b1)
Would it be possible to add this feature to the HA UniFi integration?

Also, it would be very nice if we could get the following switch main uplink "Experience" connection state into HA UniFi integration:
![Screenshot 2024-06-06 125256](https://github.com/hassio-addons/addon-unifi/assets/48346793/120d93ec-e6e1-4673-8912-93d0ab1e7cd8)

The specific main purpose in this case is the problem that I would like to reboot the switch whenever the main uplink port changes from GbE to FE connection as for some reason some type of UniFi switches are acting weird by changing from GbE to FE out of nowhere. It happens very rarely but it happens sometimes and a simple switch reboot always fixes the issue. So having the possibility to automate a switch reboot via HA would clearly be helpful.

FYI: It is clear to me that in case of a network issue the first obvious thing to do would be to resolve that issue on the network/hardware layer (i.e. defective LAN cables, poor power supply, etc.) but there are other users having exactly the same issue since months with the same model of UniFi switches, so it seems much more a hardware/firmware issue with those switches than a network issue.

Thank you very much for considering!

**Comment by frenck** [comment]
> Would it be possible to add this feature to the HA UniFi integration?

This is not the Home Assistant integration, but the issue tracker of the add-on repository.

Add-ons & integrations are not the same things.

../Frenck
