### ISSUE TITLE
Unifi USG-3p cant access controller goes offline after unifi network 8.2.93

### ISSUE THREAD

**Issue by skynet-network** [hassio-addons/addon-unifi#512]
# Problem/Motivation

> (Why the issue was filed)Unifi USG-3p cant access controller goes offline after unifi network 8.2.93

## Expected behavior

> (What you expected to happen)
That the USG-3P  is online so controller can access both wired and wireless devices

## Actual behavior

> (What actually happened)

It start to getting ready then it's goes offline

## Steps to reproduce

> (How can someone else make/see it happen)

Upgrade unifi network 8.2.93 when you have a USG-3P as a router and dhcp is on the router only 

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by cwmoriarty** [comment]
What was the last version this was functional on? Are you able to run network traces or provide logs?
