### ISSUE TITLE
Unifi add-on does not generate autobackups in /backup/unifi

### ISSUE THREAD

**Issue by user34756361233** [hassio-addons/addon-unifi#514]
# Problem/Motivation

Within the application an automatic backup can be set. Mine is set for making a back up everyday at 0530 am

## Expected behavior

/backup/unifi containing the auto backups

## Actual behavior

there are no backups available in said folder

## Steps to reproduce

setup autobackup to make regular changes, after setup time has passed check /backup/unifi, folder is empty

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
![Screenshot 2024-07-17 at 17 55 42](https://github.com/user-attachments/assets/35907ebf-e9ab-48cd-a380-25fd6f20d318)
![Screenshot 2024-07-17 at 17 57 10](https://github.com/user-attachments/assets/77bc05a6-69b4-484e-9ffb-52cb13b0257d)

**Comment by cwmoriarty** [comment]
Can you confirm what happens when you click "Download"-- are these files empty as well?

<img width="633" alt="image" src="https://github.com/user-attachments/assets/3e7bb582-1e9a-4be3-9f45-914e011ea21c">

**Comment by user34756361233** [comment]
Yes, if I choose to download there are no files (currently on 8.3.32)

![Screenshot 2024-07-19 at 19 40 48](https://github.com/user-attachments/assets/504391d2-700c-41e9-bd2d-32898698c1d5)

**Comment by cwmoriarty** [comment]
I can't repro this unfortunately.

**Comment by user34756361233** [comment]
I will remove/reinstall/reimport to see if that changes anything

**Comment by user34756361233** [comment]
After removal, installation and reimport one of the sites I want to migrate I am still in the same situation, ie no backup in the /backup/unifi folder. I will leave it for a day or 2. If no change I will reinstall from scratch and make a new site to see if that changes the situation..
