### ISSUE TITLE
[Feature Request] Implement Ingress feature of HA Addons

### ISSUE THREAD

**Issue by davidrapan** [hassio-addons/addon-unifi#515]
# Problem/Motivation

> Feature Idea

## Proposed changes

> Could be possible to use Ingress feature of HA addons?
> Ease of use, ssl, ...

**Comment by frenck** [comment]
From the documentation:

![CleanShot 2024-07-19 at 20 44 51@2x](https://github.com/user-attachments/assets/5a91b50d-2088-4dc9-a83c-ffddcdbad253)


../Frenck

**Comment by davidrapan** [comment]
Oh sorry then I had to missed that! Thanks!

**Comment by frenck** [comment]
No worries! 👍 

../Frenck
