### ISSUE TITLE
Unable to log in after 2FA enabled

### ISSUE THREAD

**Issue by pauljrich1** [hassio-addons/addon-unifi#516]
# Problem/Motivation

I can no longer connect to my unifi devices through home assistant after enabling 2FA.  I tried creating a local account, but it's still not working.  I suspect it has to do with running the Unifi Controller through Docker on my NAS.

## Expected behavior

I expected to be able to log in similar to how I used to log in before I enabled 2FA.

## Actual behavior

I get the following error "Unknown error occurred"

## Steps to reproduce

Run a unifi controller through a NAS with 2FA enabled, then try to connect it to Home Assistant.

## Proposed changes

Not sure how to fix it.

**Comment by sinclairpaul** [comment]
Is this an issue with the addon or the integration?

> I suspect it has to do with running the Unifi Controller through Docker on my NAS.

**Comment by pauljrich1** [comment]
I think it's an issue with the integration.

**Comment by sinclairpaul** [comment]
As it appears you aren't running the addon (which this is the repo for), you would need to raise issues related to the integration with Home Assistant itself.
