### ISSUE TITLE
Question: does this add on-automatically update version of the Unifi controller ? 

### ISSUE THREAD

**Issue by leonbrag** [hassio-addons/addon-unifi#518]
How does this add-on handle Unifi controller updates?
Does it need to be removed & re-added ?
Or when Unifi releases new update to controller it's updated automatically ?

thanks

**Comment by renewoensdregt** [comment]
No. The new version need to be updated in the add on. You’ll see a new release of the addon for it.
________________________________
From: leonbrag ***@***.***>
Sent: Tuesday, August 13, 2024 7:13:05 PM
To: hassio-addons/addon-unifi ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hassio-addons/addon-unifi] Question: does this add on-automatically update version of the Unifi controller ? (Issue #518)


How does this add-on handle Unifi controller updates?
Does it need to be removed & re-added ?
Or when Unifi releases new update to controller it's updated automatically ?

thanks
