### ISSUE TITLE
AP's stuck on getting ready.

### ISSUE THREAD

**Issue by ElDingo424** [hassio-addons/addon-unifi#523]
I did read the FAQ and the inform host selection is pointing to the HA ip address. 

I imported from a backup on another computer and though the AP's show they do not adopt and will switch back and forth between adopting and offline. 

I removed the AP's and tried to re-adopt, they say they adopt and move to the "Getting Ready" section. Then they stay there. There is no further info in logs (Logs set to info currently). 

SSH'ing into the AP's themselves and manually doing the set-inform command does not seem to remedy this either. Any thoughts or things I am missing?

**Comment by cwmoriarty** [comment]
I'd hit the Unifi forums. `info` will give some more information at the SSH console.

**Comment by Seinuh** [comment]
https://community.ui.com/questions/Moving-UniFi-Controller-devices-Adopting-endlessly/a89ec624-42ba-4003-98d2-7d2175e3c5e2

Give your home assistant device a static ip

After that go to settings ->> system ->> advanced.... then you see override... fill in your static ip of home assistant
