### ISSUE TITLE
v3.4.0? 

### ISSUE THREAD

**Issue by samyun** [hassio-addons/addon-unifi#526]
Hey y'all,

Just wanted to check in with @frenck about v3.4.0? I see that 5 days ago, the PR to upgrade to 8.5.6 was completed, and there was a release drafter run (https://github.com/hassio-addons/addon-unifi/actions/runs/11261752119), but no corresponding published release.

**Comment by frenck** [comment]
It will be released when it is tested and ready.

../Frenck

**Comment by samyun** [comment]
Is there a place whomever is testing is discussing what issues they're seeing that I can look at for next time? 

Are there any such issues found at this point?

**Comment by frenck** [comment]
> Is there a place whomever is testing is discussing what issues they're seeing that I can look at for next time? 

Nope, sorry.

> Are there any such issues found at this point? 

Not sure what that means or why that should be needed at all.

../Frenck

**Comment by samyun** [comment]
I'm trying to find out when I can expect a version of this add-on to be released that updates the Network Application to the latest v8.5.6. Since there was a completed PR that rev'ed the version in the Dockerfile, I was expecting the release to happen shortly after (based on the previous two releases). Since that hasn't happened, I'm asking here what's causing the delay. 

> It will be released when it is tested and ready.

Based on this, I took that to mean that you (or someone) found some issue that's causing the delay. Or maybe it's just that you haven't had time to actually test it (which is fine too, I just want to know what's going on).

**Comment by frenck** [comment]
> I'm trying to find out when I can expect a version of this add-on to be released that updates the Network Application to the latest v8.5.6.

This is an open source project I do in my spare time. There are not expectations to manage or set, nor is there any planning.

Things are ready when they are ready.

../Frenck

**Comment by samyun** [comment]
Bud, I am aware that you don't owe me or anyone else anything. 

But do you disagree it's not unreasonable for an outsider to assume you forgot to hit the "publish" button when you did all except the final step? When there was a tagged release very shortly after all of the previous PRs revving the Unifi version? 

I'm simply politely asking for a status update as a consumer of the add-on. If it's a few months away, I can fork it and switch my instance to that fork. If it's just a few days away, I can wait.

If you don't have the time to manage releases, let the community know so someone can fork it and maintain it. 

"It's ready when it's ready" is not helpful if you don't share what's blocking it from being ready.

**Comment by frenck** [comment]
> But do you disagree it's not unreasonable for an outsider to assume you forgot to hit the "publish" button when you did all except the final step?

Yes I disagree. That would mean one is shipping out stuff without testing. If you think that is normal, be my guest. I do not ship until I have confirmed it stable and working on multiple architectures.


> I'm simply politely asking for a status update as a consumer of the add-on. If it's a few months away, I can fork it and switch my instance to that fork. If it's just a few days away, I can wait.

What part of "There is no planning" and other parts above don't you get?


> If you don't have the time to manage releases, let the community know so someone can fork it and maintain it.

I didn't say that; I said I will pick up when I have spare time again. But you are free to fork it an do a better job.

Simple put, I have been clear on how this works. if you don't like it, please go away and don't use this.

Bye! 👋 

../Frenck
