### ISSUE TITLE
Inform url delivers HTTP error 400, no connection to controller possible

### ISSUE THREAD

**Issue by bavarianbytes** [hassio-addons/addon-unifi#531]
# Problem/Motivation

Access points are not adopted. I followed the the installations steps and set `Host for Inform` to the local IP address of Home Assistant.

I even tried to set the inform host via SSH on the AP. It told me:
`Adoption request sent to 'http://192.168.178.100:8080/inform'.  Use UniFi Network to complete the adopt process.`
But the request never pops up in the controller web UI.
I didn't change any port settings.

When i call the inform url `http://192.168.178.100:8080/inform` via browser i receive an error 400.

I can see the AP in the devices tab, but it seems there is no connection back to the controller:
<img width="1707" alt="Bildschirmfoto 2024-10-30 um 11 34 51" src="https://github.com/user-attachments/assets/2b24dc4f-cf99-42a4-9030-60bf607e3d9b">

## Expected behavior

HTTP status 200 from `http://192.168.178.100:8080/inform`.

## Actual behavior

HTTP status 400 `http://192.168.178.100:8080/inform`.

## Steps to reproduce

n/a

## Proposed changes

n/a

**Comment by cwmoriarty** [comment]
Wrong expectation, it sends a 400 if there's no auth. Take this to UI forums.
