### ISSUE TITLE
Multifactor Identification issue

### ISSUE THREAD

**Issue by Carrot-Fart** [hassio-addons/addon-unifi#536]
# Problem/Motivation

> New Multi Factor Identification means the Unifi Integration can't log in anymore

## Expected behavior

> Need to be able to disable multi factor id or make Home Assistant a trusted device?

## Actual behavior

> Can't see how to do this

## Steps to reproduce

> Have the Unifi addon installed and try to use the unifi integration.

## Proposed changes

> Not sure if there is a fix for it, i can still log into the Unifi Addon, i just can't use the Integration which was the main reason for having the Addon.

**Comment by Monacoslo** [comment]
same issue

**Comment by qtronixx** [comment]
I also have this problem.

**Comment by hiagocosta** [comment]
I have this issue today after backup

**Comment by dobrac** [comment]
Hi, in order to bypass the 2FA, you can create a new account in the Unifi application. That account will be local only, but it can be then used for the Home Assistant integration.

**Comment by Carrot-Fart** [comment]
> Hi, in order to bypass the 2FA, you can create a new account in the Unifi application. That account will be local only, but it can be then used for the Home Assistant integration.

Hello @dobrac 
I have tried to do that but it is coming up with "Failed to invite admin. Please ensure it's still on and connected to the internet"

Any idea on what i need to do to overcome this?

**Comment by Carrot-Fart** [comment]
I have managed to add some new users in site manager but as Site Administrator. When i try and change them to Read Only it doesn't seem to stick, its back to Site Administrator when i come back.
