### ISSUE TITLE
Access points not recognized

### ISSUE THREAD

**Issue by Monacoslo** [hassio-addons/addon-unifi#537]
# Problem/Motivation

 I am trying to add more access points. Older models (Unifi AP-AC and Unifi UAP-AC outdoor). They are connected to the same POE switch as my other Access Points (UAP-LR and UAP-PRO), tried with same ports, but are not recognized by controller.

## Expected behavior

 Access points seen on the list, ready to adoption

## Actual behavior

 Added access points are not visible on the list of access points after I connect them and perform factory reset

## Steps to reproduce

 1. Connect AP to POE port on switch
 2. Perform factory reset (10s pressing reset switch, white light starts blinking)
 3. Log in to controller and check to new AP to appear

## Proposed changes

I do not know

**Comment by e0909** [comment]
https://help.ui.com/hc/en-us/articles/204909754-Remote-Adoption-Layer-3
![image](https://github.com/user-attachments/assets/61020084-1772-456c-8695-3a3fef709721)

**Comment by riktanius** [comment]
> https://help.ui.com/hc/en-us/articles/204909754-Remote-Adoption-Layer-3 ![image](https://private-user-images.githubusercontent.com/93178538/388039433-61020084-1772-456c-8695-3a3fef709721.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxODE1ODMsIm5iZiI6MTczMjE4MTI4MywicGF0aCI6Ii85MzE3ODUzOC8zODgwMzk0MzMtNjEwMjAwODQtMTc3Mi00NTZjLTg2OTUtM2EzZmVmNzA5NzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA5MjgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYzE1MzBjMmVkNDMwY2NmNjU3NjM0MWRmMDBjMTM3MjBmNzgzZjQ3M2ZkYzE3ODhhYWIxNTk1OTIzYzk2N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wLLfHZ57iJ07CYsw4eg2MCmAHh9D9Q8W83TYzOufnds)

I have done this and nothing happens. What IP are we supposed to be using? I am using the IP of my RaspberryPI running HA OS, and it doesnt resolve. 

I can ping the IP without issue. 

There is another IP in the Unifi Dashboard, should we be using that one?

**Comment by sinclairpaul** [comment]
Please make sure you have set the correct inform address, which is a step in the documentation.

**Comment by emilianogetino** [comment]
Could you tell me where that information is located?
No matter how much I look, I don't see it.
Greetings, Thank you

**Comment by renewoensdregt** [comment]
See here : addon-unifi/unifi/DOCS.md at main · hassio-addons/addon-unifi · GitHub<https://github.com/hassio-addons/addon-unifi/blob/main/unifi/DOCS.md> bullet 7.

________________________________

**Comment by emilianogetino** [comment]
Thank you, it was my fault, after reading the documentation and following the steps everything works correctly.
All the best
Thank you
