### ISSUE TITLE
Inconsistent default value for memory_init

### ISSUE THREAD

**Issue by oncleben31** [hassio-addons/addon-unifi#54]
# Problem/Motivation

Clarification of the readme for `memory_init` default value

## Expected behavior

Finding in the documentation consistent information about the `memory_init` default value

## Actual behavior

In the documentation you use two default values: 256 and 512. Which one is the good one ?

## Steps to reproduce

read the READM.me ;-) https://github.com/hassio-addons/addon-unifi#option-memory_init

## Proposed changes

Didn't find clues in the code.

**Comment by sinclairpaul** [comment]
https://github.com/hassio-addons/addon-unifi/blob/d77eee3f7e1f6561590aa34e72a13a864d8871f5/unifi/rootfs/etc/services.d/unifi/run#L17

It is defaulted to 512 if not set.
