### ISSUE TITLE
New Request - Add to Sidebar Addon button for unifi addon

### ISSUE THREAD

**Issue by tingles2233** [hassio-addons/addon-unifi#540]
To access the web portal easily from within HASS can we get the option to "Add to Sidebar" which I have seen on other addons.

It would put a button on the sidebar(left) which opens the web portal in the main screen? Screenshots below of examples. 

![image](https://github.com/user-attachments/assets/e7404a61-3453-4834-bfba-2bc9517b52d3)

![image](https://github.com/user-attachments/assets/12ffdcdb-7d65-4dbe-ac30-0bda2b4701fb)

![image](https://github.com/user-attachments/assets/b7b35f1c-4031-48f5-b0c1-dc568ef9839c)

**Comment by sinclairpaul** [comment]
See #515, it is also listed as a Known Issue in the docs (The feature is referred to as Ingress)
