### ISSUE TITLE
Fails to start - No SSL Cert, but certfile there (used to work)

### ISSUE THREAD

**Issue by mattnewham** [hassio-addons/addon-unifi#55]
# Problem/Motivation

> Addon doesnt start, throwing error that SSL certificate doesnt exist.

Cert file is specified as "fullchain.pem"

fullchain.pem exists in /config/ssl (HASSIO)

Any steps to perform additional debug? This was working, and now fails. Not sure if I updated the HA version (most likely did).

**Comment by frenck** [comment]
`/ssl/` not `/config/ssl/`.

**Comment by mattnewham** [comment]
Apologies - the files are symlinked from that DIR. So they exist at both locations. 

Last line of Trace log:

[18:42:15] TRACE: bashio::fs.file_exists: /ssl/fullchain.pem

Then error about certfile does not exist.

Again, this was working fine, until an update to HA
