### ISSUE TITLE
There seems to be the "hacky" way of doing a partial backup

### ISSUE THREAD

**Issue by jperquin** [hassio-addons/addon-unifi#66]
There seems to be the "hacky" way of doing a partial backup, unpacking the addon, adding the config. Repacking and restoring. It would be great if the folder \data\unifi\data\sites\default could be made accessible in the same way as the backups.

_Originally posted by @almostserious in https://github.com/hassio-addons/addon-unifi/issues/35#issuecomment-491608857_

--> What are you guys using for repacking tar / tar.gz? My repackaged tar snapshot generated under macos terminal gets rejected by hassio when restoring:
[hassio.snapshots.snapshot] Can't read snapshot tarfile /data/backup/9cf8ab91.tar: "filename './snapshot.json' not found"

**Comment by frenck** [comment]
That is not an issue, but a question. We use GitHub to track issue.
I'd recommend trying the Home Assistant community forums for those types of support questions.

**Comment by jperquin** [comment]
Sorry. Will do.
