### ISSUE TITLE
Add UniFi Video Controler

### ISSUE THREAD

**Issue by majkrzak** [hassio-addons/addon-unifi#69]
Ubiquiti provides the UniFi Video Controller  which can be integrated with Hassio. Will be great to be able to use it as an addon in Hassio

Working Dockerfile is already available thx to @pducharme
https://github.com/pducharme/UniFi-Video-Controller/blob/master/Dockerfile

It might be used to gently tune current one from Network Contoller, to convert it to the Video Contoller 

<blockquote><img src="https://avatars0.githubusercontent.com/u/1879339?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/pducharme/UniFi-Video-Controller">pducharme/UniFi-Video-Controller</a></strong></div><div>Docker for Unifi-Video Controller (Ubiquiti Networks) - pducharme/UniFi-Video-Controller</div></blockquote>

**Comment by sinclairpaul** [comment]
Thanks for the request, however it shouldn't really be logged as an issue for the addon.  There was a previous request logged at https://github.com/hassio-addons/repository/issues/143

**Comment by majkrzak** [comment]
I'm not so sure, for me it looks like a part of unify addon :thinking:
And was thinking about making PR for this. It does not look really possible to make PR for addons that will cover it
