### ISSUE TITLE
Add On Needs a Version Bump

### ISSUE THREAD

**Issue by mikegrb** [hassio-addons/addon-unifi#7]
d254acd979339bed1e712ebb71de577948c36ab3 bumped the controller version to 5.8.30 but it wasn't tagged so HASS.io still shows add-on version 0.2.1 with controller version 5.8.28 as current.

There's a USG firmware update but it requires the newer controller to avoid issues.

**Comment by frenck** [comment]
Agreed!

**Comment by ccfiel** [comment]
hope this will be soon updated

**Comment by frenck** [comment]
it will I was awaiting a couple of Hassio changes that might affect this add-on. Now that is out of the way I can start rolling out updates across the board.

**Comment by ccfiel** [comment]
@frenck thanks for the update!

**Comment by frenck** [comment]
No problem!
