### ISSUE TITLE
Addon won't start

### ISSUE THREAD

**Issue by Adam-North** [hassio-addons/addon-unifi#71]
# Problem/Motivation

> The controller was running fine for a few weeks. Now it will not start

## Expected behavior

> Unifi Controller to start

## Actual behavior

> Config entry for unifi not ready yet. Retrying in 5 seconds.
10:27:01 PM – config_entries.py (WARNING) - message first occurred at 10:08:01 PM and shows up 18 times
Error connecting to the UniFi controller at 10.40.67.3
10:27:01 PM – unifi (ERROR) - message first occurred at 10:08:01 PM and shows up 18 times

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
> Config entry for unifi not ready yet. Retrying in 5 seconds.
10:27:01 PM – config_entries.py (WARNING) - message first occurred at 10:08:01 PM and shows up 18 times
Error connecting to the UniFi controller at 10.40.67.3
10:27:01 PM – unifi (ERROR) - message first occurred at 10:08:01 PM and shows up 18 times

That is Home Assistant output not add-on. If you have issues with Home Assistant integrations, please check the Home Assistant project on getting support.

Thanks 👍
