### ISSUE TITLE
New Controller Software 5.12.66

### ISSUE THREAD

**Issue by iamkevinv** [hassio-addons/addon-unifi#72]
How can we get the latest controller software into the addon? Can i help? :)

**Comment by allanpersson** [comment]
PR opened https://github.com/hassio-addons/addon-unifi/pull/73

**Comment by difelice** [comment]
How long before this is published?

**Comment by frenck** [comment]
This will happen in the upcoming days. Since the issue is resolved on dev/edge, I'll go ahead and close this "issue".

Thanks 👍

**Comment by difelice** [comment]
Thank-you!
