### ISSUE TITLE
add link on sidebar

### ISSUE THREAD

**Issue by meijerpeter** [hassio-addons/addon-unifi#75]
# Problem/Motivation

> (Why the issue was filed)
Convenience to find the link to the unifi dashboard

## Expected behavior
It would be nice to have a direct link to the unifi dashboard from the sidebar in the front-end of hassio.

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
We can't. The UniFi application won't allow it.
