### ISSUE TITLE
Device in state 'Unavailable' after HA restart

### ISSUE THREAD

**Issue by membersound** [hassio-addons/addon-unifi#77]
Problem: when a (smartphone) device that is tracked by unifi addon is not connected to the unifi AP, and the HA is restarted. Then the device will be in state "Unavailable".

This is a problem if you use the device as tracker for state `home` or `not_home`.

I think the correct solution is to put the device into `Away`(as it is when simply disconnecting the smartphone from wifi), because if it is not found within the unifi controller, it should assume the device is away.

Home Assistant 0.108.6
Unifi Controller Addon 0.14.1

**Comment by sinclairpaul** [comment]
The add on provides the Unifi Controller software itself.  The device tracker integration is provided by Home Assistant, so you would need to log your issue there.
