### ISSUE TITLE
Adopting of AP nanoHD keeps forever

### ISSUE THREAD

**Issue by stefancvetkovic** [hassio-addons/addon-unifi#79]
Hello,

RaspberryPi3 - flashed sd card with hassio image
HassOs 3.13
Home assistant  0.108.7

I install add-on, and because I know that there is some glitch with restoring backups, I decided to start from scratch.
I removed my AP from my old PC controller, and did reset-button of the device.
And when I click on a `Adopt` button it tries and tries to adopt him, but at the end `disconnected` message appears.
Is there any clue whats happening?
here are my full logs:
```[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: UniFi Controller
 Manage your UniFi network using a web browser
-----------------------------------------------------------
 Add-on version: 0.15.0
 You are running the latest version of this add-on.
 System: HassOS 3.13  (armv7 / raspberrypi3)
 Home Assistant Core: 0.108.6
 Home Assistant Supervisor: 219
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] unifi.sh: executing... 
Importing keystore /tmp/tmp.UgI3QU8Br5 to /usr/lib/unifi/data/keystore...
Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore /usr/lib/unifi/data/keystore -destkeystore /usr/lib/unifi/data/keystore -deststoretype pkcs12".
[cont-init.d] unifi.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[00:23:45] INFO: Starting the UniFi Controller...
OpenJDK Client VM warning: You have loaded library /usr/lib/unifi/lib/native/Linux/armv7/libubnt_webrtc_jni.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.```

**Comment by sinclairpaul** [comment]
Assume that the UI loads fine and you set the inform host in the GUI?

**Comment by stefancvetkovic** [comment]
Im not sure where to find that option? `Override inform host with controller hostname/IP` I found only this in Settings -> Controller -> Controller settings

**Comment by stefancvetkovic** [comment]
![image](https://user-images.githubusercontent.com/13699747/80292649-1f497100-8758-11ea-91e2-c1ddca6a5c10.png)
![image](https://user-images.githubusercontent.com/13699747/80292679-4a33c500-8758-11ea-83f2-8c7834264af4.png)

**Comment by sinclairpaul** [comment]
I am guessing you need to enable Advanced Features, then:

Settings/Controller Settings/Advanced Configuration

Likely the docs need updating due to all the UI changes, any PR's are welcome 😉

**Comment by stefancvetkovic** [comment]
@sinclairpaul  thanks but still the same, I restart add-on, and still its adopting.
maybe my Controller hostname is wrong, but I doubt it
![image](https://user-images.githubusercontent.com/13699747/80292814-b82cbc00-8759-11ea-89c8-e524a4d090dd.png)

**Comment by sinclairpaul** [comment]
I doubt the AP's can resolve via mDNS, set the IP.

There is also information in the read me on manually adopting.  Either way I doubt this is an issue with the addon itself.

**Comment by lennard7001** [comment]
I've got the same problem on a complete fresh install of Home-Assistant and the Controller with the UniFi AP AC-Lite

**Comment by Guidelajungle** [comment]
hey, i had the same problem for the Unifi ap ac-lr, fixed it using the unifi app on android. Connected trough the home assistant controller, i went into more -> remote adoption -> the same AP that could not finish adopting, adopt, blue light on the AP -> 1 minute later -> adopted and no more problems

**Comment by golddragon007** [comment]
I had a similar problem with my AP HD, you need to set up the controller's IP address in the advanced configuration. If you can't find it on the new UI you can still change it back to the old 'legacy' one.

**Comment by boomalator** [comment]
It wouldn't/couldnt adopt my Mesh Outdoor AP either. Also noticed it didn't set a hostname for the controller, but nothing i did would work, either.

**Comment by lennard0711** [comment]
Are there any updates on this? I really want to switch back to this instead of using a dedicated RPi for it.

**Comment by frenck** [comment]
There is no update on this, as this is not broken.
You need to set the correct inform address, preferably on an IP basis.

**Comment by jrc** [comment]
This is in the add-on documentation (to be fair, I missed it, which is why I'm here):

> ## Installation
> :
> 6. Go to the settings (gears icon in the bottom left) -> Controller (tab).
> 7. Change the Controller Hostname/IP to match the IP or hostname of the device running Home Assistant.
> 8. Check the box Override inform host with controller hostname/IP.
> 
> ## Known issues and limitations
> * The AP seems stuck in "adopting" state: Please read the installation instructions carefully. You need to change some controller settings in order for this add-on to work properly. Using the Ubiquiti Discovery Tool, or SSH'ing into the AP and setting the INFORM after adopting will resolve this. (see: _Manually adopting a device_)
> 

This issue should be closed.

**Comment by frenck** [comment]
Agreed.
