### ISSUE TITLE
new version available 5.9.29

### ISSUE THREAD

**Issue by ccfiel** [hassio-addons/addon-unifi#8]
there is new version available for the controller 5.9.29. When is the plan for the upgrade? Thanks!

**Comment by frenck** [comment]
Sure!
The 5.9 branch is now stable.

This is a pretty large upgrade from 5.8, so that needs to be tested carefully.
Nevertheless, you can expect an update soon.

**Comment by ccfiel** [comment]
@frenck thanks for the update! :)

**Comment by frenck** [comment]
v0.4.0 of the add-on has been released. 🎉

**Comment by ccfiel** [comment]
@frenck thanks!
