### ISSUE TITLE
hassioaddons/unifi-armv7:0.15.0 Not Found

### ISSUE THREAD

**Issue by dcsg** [hassio-addons/addon-unifi#81]
# Problem/Motivation

> Unifi controller does not start after upgrade from 0.14.1 to 0.15.0 and I don't have anything in logs.

## Expected behavior

> The unifi controller to start or have any log that reports the current problem

## Actual behavior

> (What actually happened)

## Steps to reproduce

> I'm using hassio (version  in a raspberry pi 3 b+ with the following configuration

```
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
log_level: info
memory_max: 512
memory_init: 256
```

After all I was looking in the wrong place for logs, here is the problem:  ERROR (SyncWorker_15) [supervisor.docker] Can't create container from addon_a0d7b954_unifi: 404 Client Error: Not Found ("No such image: hassioaddons/unifi-armv7:0.15.0")

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/80313392-f32b0000-87ea-11ea-9dde-0c97ee74e408.png)

It exists. A 404 usually means you don't have enough disk space to complete the download, extract and install procedure.

**Comment by dcsg** [comment]
Thansk @frenck. I had to install portainer to force the pull of the image. After pulling the image from the portainer it worked but for some reason it was not able to pull when I upgraded the addon.

Cheers.
