### ISSUE TITLE
is there a way to point HASS to an existing unifi controller?

### ISSUE THREAD

**Issue by lordmundi** [hassio-addons/addon-unifi#85]
Not sure of the best place to ask questions, but is there any way to configure HASS to use an existing Unifi Controller?  Reading through the instructions, it appears you can install the controller on the same host as HASS and even migrate settings from an existing controller to this one.  But what if you have a hardware controller?  Or a controller where you don't want it on your HASS host?  Is there any way to have HASS be able to talk with an existing Unifi Controller and get presence detection and sensor, etc.?

**Comment by sinclairpaul** [comment]
Documentation is at https://www.home-assistant.io/integrations/unifi_direct/

Specify the host when you configure the integration.

This really isn't related to the addon so will close.
