### ISSUE TITLE
Installation instructions are incomplete

### ISSUE THREAD

**Issue by majes-git** [hassio-addons/addon-unifi#88]
# Problem/Motivation
When following the installation instructions, the web ui does not come up:

> Installation
> The installation of this add-on is pretty straightforward and not different in comparison to installing any other Home Assistant add-on.
>
> Search for the "UniFi Controller" add-on in the Supervisor add-on store and install it.
> Start the "UniFi Controller" add-on.
> Check the logs of the "UniFi Controller" to see if everything went well.
> Click the "OPEN WEB UI" button, and follow the initial wizard.
> After completing the wizard, log in with the credentials just created.
> Go to the settings (gears icon in the bottom left) -> Controller (tab).
> Change the Controller Hostname/IP to match the IP or hostname of the device running Home Assistant.
> Check the box Override inform host with controller hostname/IP.
> Hit the "Apply Changes" button to activate the settings.
> Ready to go!

## Expected behavior

There should be instructions how to create the required TLS cert. Ideally the plugin would create a self-signed cert.

## Actual behavior

Web ui does not come up.

**Comment by sinclairpaul** [comment]
It does, please see the note at https://github.com/hassio-addons/addon-unifi#option-ssl

If this is still an issue, please post the addon logs and config

**Comment by majes-git** [comment]
SSL is not an "option" it is mandatory! This is why I have opened this issue. The instructions are not clear, simply add a line like "ensure you have an SSL/TLS certificate" present.

**Comment by sinclairpaul** [comment]
`ssl: false`

Then the certificate will be generated for you.  If you believe that the documentation needs clarification, please feel free to open a PR.
