### ISSUE TITLE
Open Web UI does not work when using Nabu Casa (because no Ingress)

### ISSUE THREAD

**Issue by rschuiling** [hassio-addons/addon-unifi#90]
# Problem/Motivation
When installing the UniFi controller add-on, I got stuck for a while on step 4: "Click the OPEN WEB UI button, and follow the initial wizard." Because I am using Nabu Casa and Ingress is not supported for this add-on, this does not work. My suggestion is to change step 4 of the documentation.

## Expected behavior
I expected that the configuration wizard for the add-on would show up,

## Actual behavior
ERR_CONNECTION_TIMED_OUT This site can't be reached.

## Steps to reproduce
Use Nabu Casa cloud so the URL for your HA is something like https://xxxxxxxxx.ui.nabu.casa/.
At step 4 click 'Open Web UI'.

## Proposed changes
Rephrase step 4:
Click the OPEN WEB UI button and follow the initial wizard. *Note: if you have Nabu Casa cloud configured, just browse to the URL https://[internal IP address]:8443.*

**Comment by frenck** [comment]
From the documentation:

> This add-on cannot support Ingress due to technical limitations of the UniFi software.

**Comment by rschuiling** [comment]
@frenck I think you closed this too fast. My suggestion is merely to add one sentence to the documentation. So the next user won't get stuck at step 4.

Not everyone knows that because Ingress is not supported, the Open Web UI button doesn't work.

**Comment by frenck** [comment]
Not willing to make that change, as it is covered by multiple factors already. Thank you for your suggestion though.
