### ISSUE TITLE
Addon not Available in HACS 1.0.3

### ISSUE THREAD

**Issue by Whogives23** [hassio-addons/addon-unifi#91]
# Problem/Motivation

 Unable to install Addon in HACS using instructions, or adding custom repository.
## Expected behavior

 Follow installation instructions. Profit

## Actual behavior

 Unifi controller is unavailable in HACS repository. adding custom repository returns the following error:
"Repostitory structure for v0.16.0 is not compliant"

## Steps to reproduce
1. Search for Unifi Controller under Integrations 
2. Come up Empty-handed
3. Go to Custom repositories section
4.  Add: https://github.com/hassio-addons/addon-unifi
5. See error message as stated above.

<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/addon-unifi">hassio-addons/addon-unifi</a></strong></div><div>UniFi Controller - Home Assistant Community Add-ons - hassio-addons/addon-unifi</div></blockquote>

**Comment by stocker85** [comment]
Hi whogives23
This addon is provided for hass.io And should be installed via the supervisor tab Under community addons.
HACS is something different.

**Comment by frenck** [comment]
HACS does not provide add-ons. You are mixing up integrations with add-ons. Those are not the same things. See add-on documentation on how to install it.

**Comment by Whogives23** [comment]
What an absolute idiot I am. Apologies.
And thanks for the info
