### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by lancelon** [hassio-addons/addon-unifi#94]
I've noticed that whenever I run this addon, my swap usage always sits at 100%. If I turn off the addon it goes down to 100% straight away. Is this a limitation of my hardware (Ra Pi Bv2) or a memory leak in the addon?

**Comment by nhorvath** [comment]
The unifi controller runs in a java instance that uses 512MB - 1GB RAM. Depending on what else you're doing on your Pi, it's probably just the way it's going to be. Consider upgrading your hass environment to a VM on a PC with more RAM.
