### ISSUE TITLE
[feature] UNIFI controller in HA menu

### ISSUE THREAD

**Issue by michalk-k** [hassio-addons/addon-unifi#99]
Can integration add link to the controller to HA side menu?

**Comment by frenck** [comment]
The UniFi software does not support/allow that.

**Comment by michalk-k** [comment]
For sake we misanderstood each other.
I was thinking about menu on the image below. Is it UniFi software responsibility to add the item into HA menu? I though it's the integration job.

![obrazek](https://user-images.githubusercontent.com/7868445/88302525-3b808e00-cd06-11ea-8f66-fc0ac5208df1.png)

**Comment by frenck** [comment]
That is the ingress feature, which not all software supports / can support.
UniFi cannot.

**Comment by michalk-k** [comment]
Understand. Thank you.

**Comment by tomasbedrich** [comment]
@frenck Hi, what is the limitation which disables ingress usage? I see HTTPS cannot be turned off for Unifi, but can't we do something in line with https://github.com/basnijholt/addon-otmonitor/commit/0b00bf8fa7dd03f99b484831efc6ee01b9fe2f01 = put some Nginx in front of the Unifi Controller and strip HTTPS on that? I am happy to create PR if you agree.

**Comment by frenck** [comment]
If it was that simple, I would have done it. This issue is closed and I am not bringing it back to life again.

**Comment by tomasbedrich** [comment]
I respect your view. But I am going to try on my own (and possibly fail in the end). Sharing your findings would just save me some time not to hit the same "technical limitation".

**Comment by frenck** [comment]
There are a lot of resources not respecting being hosted in a subfolder location through a reverse proxy. A large part of the application can be made available with a bunch of rewrite rules, but never got it fully stable (and at that point is was a messy beast of regular expressions already).
